### ISSUE TITLE
We should setup testing infrastructure

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#10]
Testing is an important part of ensuring high code quality. (And making sure we don't break things)

Until now, the project has been in an early prototyping form of development. We should move to something more stable as we get more users.

**Comment by osyrisrblx** [comment]
Should use TravisCI to ensure code quality.
Should check against tslint and prettier for linting/formatting.
Should run unit tests for compiling different files and make sure the compiled code is as expected.
Should run integration tests with lemur to make sure compiled code _runs_ as expected.

Optionally, use `ts-node` + `rbxsc && lemur` on the same file to see if the output is the same?
This would require some hacks like `const print = print || console.log;`

**Comment by LouieK22** [comment]
This is something I'm willing to help out with. I've got some experience with travis, testing Node code, and testing Rbx.lua code.
