### ISSUE TITLE
Invalid code generation with ternary expression in JSX expression

### ISSUE THREAD

**Issue by brianush1** [roblox-ts/roblox-ts#1061]
## Version

**roblox-ts:** 0.3.2

**@rbxts/types:** 1.0.376

## Description

When using a ternary expression in a JSX expression, it becomes the only element rendered in its parent.

## Minimal Reproduction

Make sure to install Roact, and then use the following code snippet and render it somewhere in the game:

```tsx
import Roact from "@rbxts/roact";

export class Foo extends Roact.Component {

	render() {
		return <frame>
			{true ? <frame /> : <textlabel />}
			<textbutton />
		</frame>
	}

}
```

**Expected behavior:** When this component is rendered, a frame should be created that has another child frame and textbutton.

**Current behavior:** The parent frame only includes one frame; the textbutton is not rendered.

![image](https://user-images.githubusercontent.com/11414209/86521553-72a70200-be20-11ea-8543-fc0adf8a3df4.png)

**Comment by Dog2puppy** [comment]
What's the outputted Lua?

**Comment by brianush1** [comment]
The output is
```lua
local Foo;
do
	Foo = Roact.Component:extend("Foo");
	function Foo:render()
				local _0;
				if true then
					_0 = Roact.createElement("Frame");
				else
					_0 = Roact.createElement("TextLabel");
				end;
		return Roact.createElement(
			"Frame",
			{},
			TS.Roact_combine(
				_0,
				{
					Roact.createElement("TextButton"),
				}
			)
		);
	end;
end;
```

**Comment by brianush1** [comment]
However, this seems to be fixed in the refactor branch; so, should the issue be closed?
