### ISSUE TITLE
TS 4.0 Work Items

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1062]
- [x] [Short-Circuiting Assignment Operators](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#short-circuiting-assignment-operators)
- [ ] [Enforce tsconfig.json noEmitOnError](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#build-and-noemitonerror)
- [x] [Support delete operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#breaking-changes)

**Comment by Dionysusnu** [comment]
[] Add deprecated types to auto-generator, but with [new JSDoc /** @deprecated */](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#deprecated-support) tag?
