### ISSUE TITLE
Add a way to depend on packages outside of the @rbxts scope

### ISSUE THREAD

**Issue by GeckoCoder** [roblox-ts/roblox-ts#1063]
## Suggestion

Add a way to depend on packages that are not scoped by the @rbxts namespace.

## Use Cases

With the addition of this change it should be possible to use npm registries other than npmjs.com.
This also means that is is no longer necessary  to add each user to the @rbxts organisation.

Overall this should stimulate more users to publish npm packages and give them more control over how and where to publish it.

## Examples

`Compiler Error: Imported packages must have the @rbxts scope!` <-- this should be allowed this this change

**Comment by Dionysusnu** [comment]
What other registries than npmjs.com would you want to use, why do they not work like this, and how would we make sure that packages are actually made with roblox-ts?

**Comment by jeroenkolk** [comment]
@Dionysusnu I personally prefer to publish packages to gcr.io (Google's  cloud infrastructure). Google's artifact registry, in my opinion has better version management of old artifacts.

I understand that we want to check if a package can be used in roblox-ts but the @rbxts scope does not guarantee that since everyone can join the organisation at this point in time.

This will also make it easier to share code (privately) between games someone makes.

**Comment by GeckoCoder** [comment]
@Dionysusnu I personally like to publish artifacts to gcr.io (Google's cloud infrastructure). In my opinion Google cloud has better version management for old artifacts.

I understand that we want to check if a package can actually be used by roblox-ts but the @rbxts scope is no guarantee for that since everyone can join the @rbxts organisation at this point in time.

It also makes it easier for developers to share code privately

**Comment by osyrisrblx** [comment]
@rbxts scope helps ensure people don't use random npm packages (that would never work). I don't see why other registries wouldn't support scope.

**Comment by GeckoCoder** [comment]
Can this be taken in to consideration or at least be an optional feature to disable the check?

**Comment by Dionysusnu** [comment]
You didn't answer the question.
> Why do the other registries not work like this?
