### ISSUE TITLE
Ternary assignments are transpiled with an unnessary else statement

### ISSUE THREAD

**Issue by HunterE** [roblox-ts/roblox-ts#1097]
## Version
rbxtsc -v  = 0.3.2
npm list @rbxts/types = @rbxts/types@1.0.393 

## Description
Ternary assignments are transpiled to lua with a useless else statement

## Minimal Reproduction
Make a ternary assignment ex:
```
let x = 1
let y = 2
 x = (y>x) ? y : x
```

**Expected behavior:**
```
local x = 1;
local y = 2;
if y > x then
    x = y;
end;
```

**Current behavior:**
```
local x = 1;
local y = 2;
if y > x then
   x = y;
else
end;
```

**Comment by OverHash** [comment]
Master is no longer being updated for features, bug fixes, etc. in the refactor, it creates a minimal repo:
```ts
let x = 1;
let y = 2;
x = (y>x) ? y : x;
```
compiles to
```lua
-- Compiled with roblox-ts v0.4.0
local x = 1
local y = 2
x = ((y > x) and y or x)
```

**Comment by HunterE** [comment]
Thanks for letting me know! New to this Git stuff

**Comment by OverHash** [comment]
I do highly recommend you install the refactor, it nearly has feature parity with master, and the code compiled is a lot easier to read/debug. There are extra features that master doesn't have (such as nullish coalescing operator).

To install the refactor, run the following commands in order (first CD to the desired location to install roblox-ts, I have it saved to desktop but saving to documents, etc is also pretty common):
```
git clone https://github.com/roblox-ts/roblox-ts
cd roblox-ts
git checkout refactor
npm i
npm run devlink
```

You'll need ttypescript installed beforehand (`npm i -g ttypescript`)

**Comment by HunterE** [comment]
Fantastic! Thanks for the instructions. Incidentally, I was actually just trying to use null coalescing in my project. I'll take a look at the refactor
