### ISSUE TITLE
Add for-of loop optimizations

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1110]
`Object.values`, `Object.keys`, `Object.entries`, etc.

**Comment by Validark** [comment]
If these do get optimized, we'd probably want to verify that the Object being operated on isn't modified. Personally, I wouldn't optimize these though.

If we want faster iteration without the extra step of caching the keys and values of an object, we should add an iterator directly to the Object interface, in conjunction with the submission of my PR I promised here. https://github.com/microsoft/TypeScript/issues/38388

```ts
interface Object {
	[Symbol.iterator]<T>(this: T): Generator<keyof T extends never ? [unknown, unknown] : [keyof T, NonNullable<T[keyof T]>]>;
}
```

Then, we can do:
```ts
let x = { a: 1, b:2 };

for (const [i, v] of x) print(i, v)
```

**Comment by osyrisrblx** [comment]
I like that a lot! Would really simplify things, I think. Then we can just ditch the whole `Object` variable entirely.
