### ISSUE TITLE
Generate calls to `table.create` instead of `{}` when the size of the array is known.

### ISSUE THREAD

**Issue by cntkillme** [roblox-ts/roblox-ts#1119]
## Suggestion
Generate calls to `table.create` instead of `{}` when the size of the array is known.
- [x] Array.join
- [x] Array.map
- [ ] Array concatenation within an array literal expression (e.g. `[ ...[1, 2], x, ...[3]]`)
- [ ] Array.mapFiltered? (filtered table will generally be smaller so table.create potentially over-allocates)
- [ ] Array.filter? (filtered table will generally be smaller so table.create potentially over-allocates)
- [ ] Array.reverse (deferred, see https://github.com/roblox-ts/api/projects/1)
- [ ] Array.concat (deferred, see https://github.com/roblox-ts/api/projects/1)
- [ ] Array.copy (deferred, see https://github.com/roblox-ts/api/projects/1)
- [ ] Array.slice (`(end or #arr + 1) - (start or 0)`) (deferred, see https://github.com/roblox-ts/api/projects/1)

**Comment by osyrisrblx** [comment]
> Array.splice (if/when it's implemented)
Array.splice will not be implemented, we can omit this.
