### ISSUE TITLE
Using destructured parameters from spread varArgs results in variable leaks

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#1127]
## Version

**roblox-ts:** 1.0.0-beta.0

**@rbxts/types:** n/a

## Minimal Reproduction

Let's say you want to wrap `HttpService.GetAsync` to get an `async` function, maintaining the same parameters:

```ts
const HttpService = game.GetService("HttpService");

export async function getRequest(...[url, nocache, headers]: Parameters<HttpService["GetAsync"]>) {
	return HttpService.GetAsync(url, nocache, headers);
}
```

**Expected behavior:**

```lua
local TS = _G[script]
local HttpService = game:GetService("HttpService")

local getRequest = TS.async(function(url, nocache, headers) -- optimization :D
	return HttpService:GetAsync(url, nocache, headers)
end)
```
**Current behavior:**

```lua
-- Compiled with roblox-ts v1.0.0-beta.0
local TS = _G[script]
local HttpService = game:GetService("HttpService")
local url, nocache, headers -- we got a leaker!
local getRequest = TS.async(function(...)
	local _0 = { ... } -- this is unnecessary
	local url = _0[1]
	local nocache = _0[2]
	local headers = _0[3]
	return HttpService:GetAsync(url, nocache, headers)
end)
```

## Playground link
[Link here](https://roblox-ts.com/playground/#code/MYewdgzgLgBAElKAHAygUwE4DcCWw0wC8MA5gIYC2aAdAOJpTrZ5oAUARAsk7vuwJQBuAFDC0ADyQgMsMhACeYYDABmAVyVQc4UgwBKaAI5q00VtQsBtNRgA2AGhhgQwMsAAWaR57IATTBAAugBcMAAKZBiUDAEAPFyomLxoluz0UACCCkrsgQB8-DAA3sIAkBgMNmDwiInM+HQMWYrArDYOTi5unt5ofgFCwgC+QA).

**Comment by osyrisrblx** [comment]
Made a separate issue for the parameter optimization. This one will track the hoisting bug.
