### ISSUE TITLE
Object.entries creates unused temp var

### ISSUE THREAD

**Issue by OverHash** [roblox-ts/roblox-ts#1139]
## Version

**roblox-ts:** 1.0.0-beta.1 (master commit [#b88d6dd](https://github.com/roblox-ts/roblox-ts/commit/b88d6dd4ae797d37936358a7cf912676823e8a5d))

**@rbxts/types:** N/A

## Description
roblox-ts will create unused temp variables when using Object.entries on a pre-made object.

## Minimal Reproduction
```ts
const obj = {}

for (const [i, v] of Object.entries(obj)) {

}
```
Note: This issue will not occur if making the object inside `Object.entries`

**Expected behavior:**
Emit to be
```lua
local obj = {}
local _0 = obj
-- ▼ ObjectConstructor.entries ▼
local _1 = {}
local _2 = 0
for _3, _4 in pairs(_0) do
	_2 += 1
	_1[_2] = { _3, _4 }
end
-- ▲ ObjectConstructor.entries ▲
for _, _3 in ipairs(_1) do
	local i = _3[1]
	local v = _3[2]
end
```

**Current behavior:**
```lua
local obj = {}
local _0 = Object -- !!!
local _1 = obj
-- ▼ ObjectConstructor.entries ▼
local _2 = {}
local _3 = 0
for _4, _5 in pairs(_1) do
	_3 += 1
	_2[_3] = { _4, _5 }
end
-- ▲ ObjectConstructor.entries ▲
for _, _4 in ipairs(_2) do
	local i = _4[1]
	local v = _4[2]
end
```

## Playground link
[Link here](https://roblox-ts.com/playground/#code/MYewdgzgLgBCBGArGBeGBvAvgKGwMxACcYAKUSWAbQEsAaGANwF048YB5JAU2CgDouYKIWpcIJBIgCUUjLhzYuADwAORWFgDcQA).

**Comment by osyrisrblx** [comment]
The `Object.*` functions are the only property call macros where the initial expression (`Object`) is never actually used. We should probably just wait to remove those functions instead of fixing this bug. Keeping the issue open to track this.
