### ISSUE TITLE
varArgs destructured from varArgs incorrectly errors

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#1140]
## Version

**roblox-ts:** 1.0.0-beta.2

**@rbxts/types:** n/a

## Minimal Reproduction

**Situation:**
Similar to #1127, let's say you wanted to wrap the API of `HttpService:GetAsync` but wanted to do something with the `url` arguement.
 

```ts
const http = game.GetService("HttpService")

async function getRequest(...[url, ...args]: Parameters<HttpService["GetAsync"]>) {
	print(`Sending a Get Request to ${url}`)
	http.GetAsync(url, ...args);
}
```

**Expected behavior:**

```ts
local http = game:GetService("HttpService")
local getRequest = TS.async(function(url, ...)
	print("Sending a Get Request to " .. url)
	http:GetAsync(url, ...)
end)
```

**Current behavior:**

errors

## Playground link
[Link here](https://roblox-ts.com/playground/#code/MYewdgzgLgBAFlKAHGBeGBzAhgWwKYB0A4nlAMp4BOAbgJbB4AUARABKJIU317MCUAbgBQQrBACeYYDABmAVylRa4TKQBKeAI5y80RgQMBtOZQA2AGhgGCWShggBdAFwwACrdykqEADztkXHQMhswkUACCElLMDgB8fDAA3kIAkEiUtGBQjAAGFGAAJpkYMFgwYTAa2rqwUCAwACSJJqYAvjmCqQjIxKSRksCMLZbWtvadrUJAA).

**Comment by osyrisrblx** [comment]
Closing this in favor of #1142
