### ISSUE TITLE
Cannot check if optional method exists in class

### ISSUE THREAD

**Issue by Fireboltofdeath** [roblox-ts/roblox-ts#1146]
## Version

**roblox-ts:** 1.0.0-beta.3

**@rbxts/types:** 1.0.417

## Description

roblox-ts will throw an error whenever you try to check if an optional method of a class exists, or when using the bang operator.

## Minimal Reproduction

```ts
class Module {
	OptionalMethod?(): void;
}
let instance = new Module();

if (instance.OptionalMethod !== undefined) {} // Error: Cannot index a method without calling it!
instance.OptionalMethod!(); // Error: Cannot index a method without calling it!
```
**Expected behavior:**

Should compile without throwing an error.

**Current behavior:**

Throws the following error: `Cannot index a method without calling it!`

## Playground link

[https://roblox-ts.com/playground/#code/MYGwhgzhAECyD2ATAriAptA3gKAJAHkAHAFwEt4A7MEWNYgCyQH4AKASgC5oA3eUxANzYAvtnTFopChGJgKwDAF5oFNAHc4SVGnZDsAen3QAxAEYANNABGYRNlIAzaCyky5CgHREylarQZI0ACEisrIFIhoDlJoiGxY0KIGRsYATJY2dq6y8mheJORUNHSMiEG62MkmAMyWAObwSPbSOZ7ehX4lzB66QA](https://roblox-ts.com/playground/#code/MYGwhgzhAECyD2ATAriAptA3gKAJAHkAHAFwEt4A7MEWNYgCyQH4AKASgC5oA3eUxANzYAvtnTFopChGJgKwDAF5oFNAHc4SVGnZDsAen3QAxAEYANNABGYRNlIAzaCyky5CgHREylarQZI0ACEisrIFIhoDlJoiGxY0KIGRsYATJY2dq6y8mheJORUNHSMiEG62MkmAMyWAObwSPbSOZ7ehX4lzB66QA)

**Comment by osyrisrblx** [comment]
Sounds like the "method index without call needs to be a bit more robust. The idea is to prevent things like:
`part.Touched.Connect(foo.bar)` where `bar` is a method.

So maybe we should allow specific parents nodes:
- BinaryExpression
- UnaryExpression

+ use `skipUpwards` to ignore parentheses + type assertions
