### ISSUE TITLE
Rbxtsc init game issue

### ISSUE THREAD

**Issue by mcbrowny35** [roblox-ts/roblox-ts#1170]
Rbxtsc is not digitally signed? 'rbxtsc init game' does not work, though I have used other npm packages I didn't run into this issue

**Comment by osyrisrblx** [comment]
Sounds like this problem: https://github.com/roblox-ts/roblox-ts/discussions/1173

**Comment by loplkc** [comment]
Just ran into this issue, but the link is dead. Any updates on this?
