### ISSUE TITLE
Error: Assertion Failed! - idk why it do that

### ISSUE THREAD

**Issue by ViniDalvino** [roblox-ts/roblox-ts#1183]
## Version

**roblox-ts:** 1.0.0-beta.8

**@rbxts/types:** +-- @rbxts/types@1.0.428
`-- @rbxts/validate-tree@1.0.6
  `-- @rbxts/types@1.0.428  deduped

## Description
Error: Assertion Failed!  in my code. idk why. here is the crash log:
```
[6:20:01 PM] Starting compilation in watch mode...

Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
    at Object.assert (C:\Program Files\nodejs\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformExpression (C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\nodes\expression    at C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\util\ensureTransformOrder.js:13:84   
    at C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:103:59     
    at TransformState.capturePrereqs (C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:98:9)
    at TransformState.capture (C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:103:30)
    at C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\util\ensureTransformOrder.js:13:70   
    at Array.map (<anonymous>)
    at Object.ensureTransformOrder (C:\Program Files\nodejs\node_modules\roblox-ts\out\TSTransformer\util\ensureTransformOrder.js:13:44)
```
## Minimal Reproduction

1. Install these dependencies:
```
  "devDependencies": {
    "@rbxts/compiler-types": "^1.0.0-beta.8.0",
    "@rbxts/types": "^1.0.428"
  },
  "dependencies": {
    "@rbxts/color": "^0.1.3",
    "@rbxts/roact": "^1.3.0-ts.7",
    "@rbxts/services": "^1.1.2",
    "@rbxts/validate-tree": "^1.0.6",
    "rbxts-transform-debug": "^0.1.0"
  }
```
2. Insert the code that I linked in the playground and put it in a file
3. Run rbxtsc in watch mode
4. make a change so it trigger the watch mode
5. rbxtsc should crash
**Expected behavior:**
rbxtsc shouldn't crash 
**Current behavior:**
rbxtsc crash

## Playground link
[Link here](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgUAbzgAmQBQBYE8DOwDGOAygKZQBuBJANCsgEolgA2BAhjCQCZEzRsBzEnAC+yAGZQIIZACIAAlABGADxg4A9DjKV8JHLIDccOOICuAO3wxgEC8m0wAshC4lmAQSsZo3ABRgbFAkFjAAXMgubszIAD7IAJIWODBsVjTIafg+wVwRShAQzCRpAJSIdOLQyH74dinI2cDMXMgQ4siBwaEAdADiJDAAwhjNXN1+peWoSKiowB21oy09CTgefrIAQmzaaEEwsqVx8U0raxuyTvoY+7BH03OoZ1w9Xtm+rQC8md6fxnRUI4ou53jl-C9qL8PrlSsZUCJRCZzFYbHYHIMQcwhmkhkVgG4AkEQuFIq53HFEslUukofhcfi3PlCsUyhVUFUoDU6tTGstWu1OsTegNhvyJlM6LM5gtufzVutNjs9gcjic+WMFZdrjhbqrJU9nvKcRY8cxWG5kD96abGSR4XN3NpkLKlpqLpssQ9AXNgeTsQyLSQ3S06YGCSQ4XREYjTJZrLZ7H7ogAVKBpHBdEL4LBE7qkrGUpIpLIZGDp5JZqxYCIWMwgJRkcrSznc+owDUtNodKswfqDEZjCWPaXzRYvLVK3YkO6HY6xU7yj1XG6z71PUdzCdpjNVnNW5Dl3fCnMOhE+5PuHeVk+5yGHiuZ29R8+xlEJ9HBEAQcgkAAyoBKF4XApqMFgCDgSxBGw1hkBEWLNpU1S1O2nYCh02TQbBUD9mKQ4hJMI4+hoGjyOoAC0wACBYvg+l+P7-oBwGgcA4GQS8L4yosACEE7LgAEvWaQQASaoAGRicgvFLoqVwQHwUAAGwACJHD6qASWhPQAHJsCAJBSV8PyyPxJRcLIyCaROun6YZxkAKpgGA2hQCm0A4BAakbupWnKfo5YQLmnHnq+yLxmiSYDvieB2H0UhmGAeYkhExY0noUICPFYARCkUCsQIiEcshPINF0HaCr2uGDi0w5Sj6rplZO2zTmu87xI1y46nq9wGnMm6oJguAEMQOhUD0pAwLOZqsDFFhxRACV5jAGVZcFyCIqFcaoomLrJGQzj+kkfAjFhnBQFB6bYSl1KllC37RNdJbpIVEjFahLzdsg93uFV4oEb1m4TncJIHphl1nWeu0uQd0RHRAJ3g2QIZcHS-KcTGJgaAAVFjKBY8g2nyYeGAGSwbBYGQUIJJkMipMwADW+WZAUZgdjAJONGYKTSJ0zDk2QX3+njGhwCVHYAPriwA0gk9BbAAmuLQwAPJ-gkRAJMr2ni309DK-ZaAHrIRhwCQKiQLAEjhTtaB8xTrkQFiAR23B6Au1Ad3+vB-qUsqM4HC9JHIKKvP81AADkOB8qdZB0GL0eI1yPxk-bPQIzBZ3qinZBpxgMdQB4XBuK8ADqbDADAkwOkHE0JxnZCR+geUgEEWCzoeEAOGAJDcA3UdoM3reznQ30xD8o9p8wdjBlGdBB2C1RpK0Lf0wZrANlHR43vmc+kRRVE0cEdCXp4fy5Bd9cew+ZiRtXe84JR1G0UCmL+iaZoRhf2FQuIbDMNonESJkQfgfZ+GIYZXkfHuO8edE5QgAIycXjgULgWADwTwAGKsS4FgqAKRqpcCVK4LAaoAD8pDkCWDcOIVi3AHSum4igrAREnjsykAAdzkB4c0gtoib0fJyfSrRWJ8EyKHe2X0uYdjzr+MRZVkAWD0twZATDMhRwro3AQIlwIdxUQZWQPoADUcgubKN2E3UAQ9VQOg2sgIB+8n5H1QBPAelioBtwOAeJhd976P0PsII0+ceiuJbu49uPxvG72AX4sBYNL7BMHmEg4OklFG0Ei3GiBJ6CFEmtYkwqAa6DEaEUGaO1MoLTAA4Tu7MODiLIFHG0NEOx1HNBGZA7CSb2HZiQNBxIu49zcHg4+UVSmxSyn4UeUJJYyzlorFWasNZax1nrA2s8CkaGQPZRRZ9eHuGGRA0+MJ-CTIkH-ABAJ1lUmhv03uXJR67VEXE7CUSHH+LoKxaGWI4bp2wl-M6UJMwDKbHPfGJc84diwAtZAXBO4k2CC6KOShdjsHNGg-AU8LBMxwPgPKYB1C-FaGTfATNukyBEdUjmTzM5VBaALLGItUDFGaXYAK5oyAOlEEAA).

**Comment by ViniDalvino** [comment]
PS: I know I am shooting myself in the foot by using `//@ts-ignore` but please don't complain about it unless you fix my code so the error where they would be without `//@ts-ignore`  lol.

**Comment by OverHash** [comment]
> PS: I know I am shooting myself in the foot by using `//@ts-ignore` but please don't complain about it unless you fix my code so the error where they would be without `//@ts-ignore` lol.

The issue here is that `RBXScriptSignal:Wait()` can return multiple values, so it is a tuple. Your code *will* error when it does successfully compile. Perhaps you meant to do this:
```ts
const character = player.Character ?? player.CharacterAdded.Wait()[0];
```

**Comment by OverHash** [comment]
```ts
insertModelIntoCharacter(character, speeder);
``` is the offending LoC. `speeder` is of type `any` and was never actually declared, causing roblox-ts to throw the compiler error.

To be honest, this isn't really roblox-ts's fault. Your code is very unsafe and you are misusing roblox-ts if you `ts-ignore` everything.
