### ISSUE TITLE
Compiling an opcall with the argument array as unknown[] errors

### ISSUE THREAD

**Issue by Mixu78** [roblox-ts/roblox-ts#1185]
## Version

**roblox-ts:** 1.0.0-beta.10

**@rbxts/types:**  1.0.428

## Description

When calling opcall<unknown[], any> with a spread array as extra arguments, the compiler errors with "Assertion Failed!".

## Minimal Reproduction
```ts
opcall<unknown[], any>(() => {}, ...[]);
````

**Expected behavior:**

The compiler compiles and emits the code properly.

**Current behavior:**

The compiler tries to compile this and errors with "Assertion Failed!".

## Playground link
[Link here](https://roblox-ts.com/playground/#code/PYBwxghgNlA8CuA7A1o4B3RBtAugGgAIJEBPAPgAoKBKAgXjIIG8BfQgOk92oG4g).

**Comment by osyrisrblx** [comment]
Looks like it's actually the use of the spread in the second arg that causes the crash.

**Comment by Dionysusnu** [comment]
This is actually #1049, spread expression in a macro.
