### ISSUE TITLE
string.sub() is 1-based

### ISSUE THREAD

**Issue by hughanderson4** [roblox-ts/roblox-ts#1186]
## Version

**roblox-ts:** 1.0.0-beta.10

**@rbxts/types:** 1.0.428

## Description
`string.sub()` uses 1-based index for addressing characters of the string

## Minimal Reproduction
`'abcdef'.sub(1,2) === 'ab'`

**Expected behavior:**

Expect to use 0-based indexing as other string and array utils.
`'abcdef'.sub(1,2) === 'bc'`

**Comment by OverHash** [comment]
As of [1.0.0-beta.5](https://github.com/roblox-ts/roblox-ts/releases/tag/1.0.0-beta.5) some string methods use 1-based indexing as it's easier to program with.

**Comment by hughanderson4** [comment]
@osyrisrblx I noticed the docs are out of sync with this 1-based behavior.
https://roblox-ts.com/docs/usage/behavior-changes#strings-and-arrays-are-zero-indexed

**Comment by osyrisrblx** [comment]
Sorry, the docs are very out of date. I'm planning to go back and rewrite all of them soon.
