### ISSUE TITLE
Object.entries/keys/values does not compile

### ISSUE THREAD

**Issue by hughanderson4** [roblox-ts/roblox-ts#1187]
## Version

**roblox-ts:** 1.0.0-beta.10

**@rbxts/types:** 1.0.429

## Description
Trying to use `Object.entries()`, `Object.keys()`, and `Object.values()` as described in the [Iteration page of guide](https://roblox-ts.com/docs/guides/iteration) results in a compile-time error like `error TS2693: 'Object' only refers to a type, but is being used as a value here.`

## Minimal Reproduction

```ts
    const obj = { a: 1, b: 2, c: 3 } as const;
    const entries = Object.entries(obj);
    const keys = Object.keys(obj);
    const values = Object.values(obj);
````

![image](https://user-images.githubusercontent.com/2387520/102719983-43e1f280-42bf-11eb-9265-9124f61160cf.png)

**Expected behavior:**
Expect it should work as described in the [Iteration page of guide](https://roblox-ts.com/docs/guides/iteration)

**Current behavior:**
Cannot use `Object.*` functionality since it can't be compiled.

## Playground link
[Reproducible in this Playground](https://roblox-ts.com/playground/#code/AQ4YwewOwZwF2BARgK2AXmAb2AQwFzACMANMEoQExliEDMwAvnjONPANwBQobsCAUyhwATgEsBrTAHlUAsHAB0Q0RJgAKZCgCU3XpH7AA1gICeU4LJTylJ85tS6eoA-GAA3XABsArpIyWcgqKnr6SDjocQA).

**Comment by tacheometry** [comment]
You have to import it from `@rbxts/object-utils`. The Object.* functions got removed in `v1.0.0-beta.5`:
```ts
import Object from "@rbxts/object-utils";
```

**Comment by hughanderson4** [comment]
Actually you can try every red "Compile" link on Iteration page and they all go to Playgrounds who display errors.

**Comment by hughanderson4** [comment]
Thanks, I'm now unblocked by adding `object-utils` dependency.  Recommend to update docs/examples to reflect this requirement.

I sincerely appreciate all you do!!!!!
