### ISSUE TITLE
"rbxtsc init" should error on invalid "npm init" folder name

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1188]
If your project folder name has spaces in it, npm will error and crash the initialization process halfway through.

Instead, we should emit our own error that clarifies this before doing anything.

**Comment by Nickuhhh** [comment]
![image](https://user-images.githubusercontent.com/25470747/102728729-79a4cc80-42fb-11eb-8733-8154420fbe29.png)
Current error message.

**Comment by Dionysusnu** [comment]
A simpler way which handles more edge cases might be to re-run init without the -silent flag, and then use that as error?
