### ISSUE TITLE
Compiler errors when importing scoped packages

### ISSUE THREAD

**Issue by uhm-jade** [roblox-ts/roblox-ts#120]
Steps to reproduce:

1. Install a scoped npm package (e.g. `npm install @my-username/rbx-foobar`).
2. Import the package somewhere in the project code.
2. Run rbxtsc.

Interestingly, the module will still build as long as you _don't_ import the package.

**Comment by Validark** [comment]
Is this fixed?

**Comment by osyrisrblx** [comment]
Yes but we only support the @rbxts scope. Closing this.
