### ISSUE TITLE
Function declarations are not hoisted, causing the compiler to emit non-functioning code.

### ISSUE THREAD

**Issue by jagatse** [roblox-ts/roblox-ts#1200]
## Version

**roblox-ts:**  1.0.0-beta.10

**@rbxts/types:** 1.0.428 

## Description

In TypeScript (well, JavaScript really), function declarations are hoisted, meaning that they behave as if declared at the top of the enclosing scope when the program executes. See https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

As I understand it, the actual hoisting is made by the JavaScript engine when the program executes. Since the Lua engine does not perform hoisting, the roblox-ts compiler needs to perform the hoisting before it emits the Lua code.

## Minimal Reproduction

The issue can be illustrated by the following snippet (also see the playground link below):
```typescript
let x = 5;

// This compiles to a call to a nil value.
let y = add3(x); 

function add3(v: number) {
    return v + 3;
}

function foo(v: number) {
    const z = add7(v);
    return z

    // No code at all is emitted for this function.
    function add7(n: number) {
        return n + 7;
    }
}

print(`y: ${y}, foo(3): ${foo(3)}`);
```

**Expected behavior:**

For each scope, the compiler should emit Lua code for the functions declared in that scope before it emits Lua code for the actual code in the scope.

**Current behavior:**

The compiler emits code that crashes when it executes. The Lua code emitted for the code snippet above is:
```lua
-- Compiled with roblox-ts v1.0.0-beta.11
local x = 5
-- This compiles to a call to a nil value.
local add3
local y = add3(x)
function add3(v)
	return v + 3
end
local function foo(v)
	local add7
	local z = add7(v)
	return z
end
print("y: " .. tostring(y) .. ", foo(3): " .. tostring(foo(3)))
return nil
```

## Playground link
[Playground link to code snippet above.](https://roblox-ts.com/playground/#code/DYUwLgBAHhC8EFYDcAoFB6dEAqALAlgM4QDGA9gLYAO+oxYZEAhqU8MBA8xAHa0QA3NgFcQAOhShIATzjMAJvIDMACigBKVCgBmwniTD4yPBcpUCAXL2EUARiABO6iAG8UEDxAfhhDkwIgAagglVABfNF19Q2MIbTIycyseG3snV3dPch5CSAAvOSZFAHZzTUyPbzBfEzy0TwhMCAA5RnJ5EGZINg4iCBAKfDAwEHk4sgdOAmIogyMeCQbZmJMi+VKeZNTHZzcGhqqa3iCIYtQGiIiUKgd8HjAVAANpKwASF2kwgBpxxKV1N4ueJ-dRhR6aIA).

**Comment by osyrisrblx** [comment]
For now, this is by design.

You can see in the compiled code we do hoist the variable declaration, but not the value. This allows you to do things like:
```Lua
function foo() {
    bar();
}

// foo(); // not this!

function bar() {
}

foo(); // but this!
```

The problem with hoisting the entire body of the function is that it would get really hard to untangle how references variables get hoisted as well.

Will consider this for the future, but for now I don't think it's reasonable to support.

**Comment by jagatse** [comment]
@osyrisrblx , First of all, a big THANK YOU to you and the team for roblox-ts. To be able to use TypeScript and VS Code to program Roblox is really great!

Second, if not hoisting function declarations is by design, I think it is worth mentioning in the documentation. There used to be a page describing TypeScript features that are not supported, but the documentation pages seems to be undergoing a big change and I can no longer find that page. I assume it will come back in some form.

Third, if you can spare the time, can you explain what is hard about hoisting function declarations? I don't understand your comment:
> The problem with hoisting the entire body of the function is that it would get really hard to untangle how references variables get hoisted as well.

Is this related to performance of the resulting Lua code somehow? I know very little about Lua, so I can't tell.

Perhaps I am naïve, but I don't see the hard part of performing the hoisting transformation. I imagine it can be made when the Lua code is generated simply by, for each block (scope):
1. Generate declarations for all variables in the block.
2. Generate assignment of functions for all functions in the block declared with the function keyword in the ts source.
3. Generate Lua for the rest of the statements in the block. 

Can you think of a situation where this simple algorithm will generate incorrect, inefficient or otherwise unwanted code?
