### ISSUE TITLE
ROBUX Scam from ur partnered Microsoft ??

### ISSUE THREAD

**Issue by LolalrikofficialYT** [roblox-ts/roblox-ts#1201]
Why Why Why Roblox and microsoft did u remove the free robux , and also its not fair that u guys are not allowing other countries to have it. Is this a joke , I waited on ur website for 3 hours after I received the free 100 robux but it showed me an error , and it said that this product is unavailable , wtf is wrong with guys , pls send me the robux code  ASAP, 
I have the right to get it cause I did all the steps . Send me the code here : ralrik31@outlook.com or ralrik31@yahoo.com , I better see my robux code in my outlook email by tommorow 31/12/2020

It better be there 😠

I did not sit there in ur stupid website for 3 hours  to see this error.

**Comment by OverHash** [comment]
roblox-ts is in no way affiliated to Microsoft or Roblox.

This issue is completely out of anyone who works on roblox-ts's hands, you'll want to direct your support request to either Roblox or to Microsoft's support lines.
