### ISSUE TITLE
Roact TSX: Spreading an object with a Key property results in incorrect behavior

### ISSUE THREAD

**Issue by tacheometry** [roblox-ts/roblox-ts#1252]
## Version

**roblox-ts:** 1.0.0-beta.15

**@rbxts/types:** 1.0.444

## Description

When spreading an object with a `Key` property inside an intrinsic element's props (as to name the Roblox instance) with `{...someObj}`, an error gets thrown at runtime by Roact:
```
Error applying props:
	Key is not a valid member of TextLabel "TextLabel"
```

## Minimal Reproduction

```ts
import Roact from "@rbxts/roact";

const myProperties = {
    Key: "This is a custom name"
}

const LocalPlayer = game.GetService("Players").LocalPlayer;

Roact.mount(
    <screengui>
        <textlabel
            {...myProperties}
        />
    </screengui>,
    LocalPlayer.WaitForChild("PlayerGui")
);
```

**Expected behavior:**

The TextLabel's name should have been set to `This is a custom name`.

**Current behavior:**

The compiler doesn't recognize `Key` as me wanting to set the instance's name, passing this down to the Lua code, resulting in Roact throwing an error:
![image](https://user-images.githubusercontent.com/39647014/107106763-e20d2600-6835-11eb-8f65-f20e0e47cdcc.png)

## Playground link
[Link](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCdQgDsL4QBPABWxgAprGBCKcALxwA3kzgK4AaSE8AXPgAqAC2AS9cZHFQBXLjjjtkIIXiYBfFm07wAMhFTIANny-IeIlJwAObWQgB0AOJCMADKIgBuwKhCABR4vv4iFHgAlOHunj5+AVDMTEh04SAQJuwwqfKKADwUqFBCQuzBJsAAfE2KLTBC5H7EQl6DQzMy4fO8AhDCouKOM4pUA0PNVG0dXT39ADTThd6ZpeEA6sjAMABi0ADCul4AJumXIpG9eUy5BhAA)

**Comment by Vorlias** [comment]
It's because `Key` is actually a compiler property, like `Change` and `Event` (which you will find this issue happens with as well)

Honestly don't know if this is worth supporting, because then you have to do weird exception checks with the iteration of properties in the compiled code, and that'd get quite messy.

**Comment by osyrisrblx** [comment]
This is a tricky one for all the reasons @Vorlias mentioned.

It's also very hard for us to detect from a compiler perspective.
