### ISSUE TITLE
Invalid ReadonlyMap typings / transpile

### ISSUE THREAD

**Issue by Polo1K** [roblox-ts/roblox-ts#1268]
## Description

	let entries = undefined;

	const map = new ReadonlyMap<K, V>(entries);

Typing for maps support undefined entries, when a variable that is undefined is passed rather than no arguments, the ipairs loop is added in the transpile when it should not be

Exception: invalid argument #1 to 'ipairs' (table expected, got nil)

	local _1 = {}
	for _, _2 in ipairs(entries) do
		_1[_2[1]] = _2[2]
	end

**Comment by osyrisrblx** [comment]
Fixed this in `@rbxts/compiler-types@1.0.0-beta.15.1`
