### ISSUE TITLE
Unknown issue in function causes compiler to error

### ISSUE THREAD

**Issue by ReturnedTrue** [roblox-ts/roblox-ts#1286]
## Version
**roblox-ts:** 1.0.0.beta-.16
**@rbxts/types:** 1.0.456

## Description
A simple function I created to output a formatted string seems to cause a compiler error because an 'assertion failed':
![Image](https://i.imgur.com/VvJtqKT.png)

## Minimal Reproduction
This function here will replicate the same error:
```ts
function output(message: string, ...args: Array<string | number>)
{
    print("OUTPUT: " + message.format(...args));
}
```

## Playground link
[Link](https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABHEUAOqAUBbApgZ3wEMBzXALkXygCcYwSAaRAOjaJpP0oEEaaiATwA81Og0QAfRGBDYARrhoA+AJQAoAN7rEuxGnFRMAIgDyAVQAqABSuVjiANSI8hUrhbA4NbESNsWDi5VVQBudQBfdXUgA)

**Comment by Fireboltofdeath** [comment]
Macro methods don't currently support spread syntax. https://github.com/roblox-ts/roblox-ts/issues/1149

**Comment by ReturnedTrue** [comment]
Ah I see, thank you.
