### ISSUE TITLE
Macros in else if statement should not be hoisted

### ISSUE THREAD

**Issue by Fireboltofdeath** [roblox-ts/roblox-ts#1314]
## Version

**roblox-ts:** 1.0.0

## Description
Macros will be hoisted above the initial if statement when present in an `else if` condition.

## Minimal Reproduction
```ts
const array = [1];
if (true) {
} else if (array.pop() === 1) {}

print(array.size()); // should be 1, but is 0
```

**Expected behavior:**

The macro should not be hoisted above the initial if statement, similar to how macros in if statements already work (see playground link)

**Current behavior:**

A value of the array will always be popped, even though the condition should never actually be evaluated.

## Playground link
[Link here](https://roblox-ts.com/playground/#code/MYewdgzgLgBAhgJwTAvDMBTA7jAgkuATwB5oEBLMAcwD4AKASgG4AoRBAOgAcBXCACzoAiIQBoYI5ixYB6GTCj9yEGKAC2XcgBsMKyqCQZgULYWnkAZjDpq4ijgjhgAJiDWMYNGAAYGMAN4sMMEwXBRgUMKgLuRQ5OAwyvBaWEQqUAg8GEJSAL4wGFoQGIlWdOzcIFweKLUSOQFBIWGUkULkGiAQEOQARjqq4M6x8WAwAIw5rLnScgpKKuqaOosghsam5mW29o4ubh7EPjAAZCfwSJXVfrVoko0hoeFtHVxdPf0l0cNxCQBMUxYMxYLQi5UuPQAXhhGMwYHMBCAeFpnDBeiU-uJejxYElxkA).

**Comment by Dionysusnu** [comment]
I believe we had a similar issue before, and already fixed it back then. Maybe our check doesn't catch an edge case here?

**Comment by Fireboltofdeath** [comment]
> I believe we had a similar issue before, and already fixed it back then. Maybe our check doesn't catch an edge case here?

I'm not sure specifically what issue you're referring to, but maybe you're thinking of if statements (not else if), which is handled correctly as shown in the playground link.

**Comment by Validark** [comment]
I believe I fixed this in the old compiler fairly easily, all you have to do is emit the rest of your elseif's in an else branch:

```lua
-- Compiled with https://roblox-ts.github.io v0.3.2
-- March 21, 2021, 8:45 AM Central Daylight Time

local array = { 1 };
if true then
else
	local _0 = #array;
	local _1 = array[_0];
	array[_0] = nil;
	if _1 == 1 then
	end;
end;
print(#array);
```
