### ISSUE TITLE
LuaTuples don't compile correctly with optional chaining

### ISSUE THREAD

**Issue by alihsaas** [roblox-ts/roblox-ts#1338]
## Version

**roblox-ts:** 1.1.1

**@rbxts/types:** 1.0.468

## Minimal Reproduction
```ts
interface Notification {
    Message?: string
}

const notification: Notification = {}

notification.Message?.gsub("<.->", "")[0]
```
compiles to
```lua
-- Compiled with roblox-ts v1.1.1
local notification = {}
local _0 = notification.Message
if _0 ~= nil then
	_0 = string.gsub(_0, "<.->", "")[1]
end
return nil
```
`string.gsub(_0, "<.->", "")[1]` should be `(string.gsub(_0, "<.->", ""))`
and should use select for other indexes

## Playground link
https://roblox-ts.com/playground/#code/JYOwLgpgTgZghgYwgAgHIHszBsBcvojIDeAUMhcgLIQDOtcA5hAPwBcytYUojpAvqVIJCXZCEzZc+YIQ4YsOPASIBeEoNITF0lQDoa9Jqz2NaAVwBGACgBEAHj0BaAHy2ANMlu2AlAG0ABgBdIA

**Comment by Dionysusnu** [comment]
Part of bigger longstanding issue, LuaTuple type doesn't get detected in unions/intersections
