### ISSUE TITLE
Inferred callback override on methods is ignored

### ISSUE THREAD

**Issue by xethlyx** [roblox-ts/roblox-ts#1342]
## Version

**roblox-ts:** 1.1.1

**@rbxts/types:** 1.0.469

## Description

Inferred callback override on methods is ignored

## Minimal Reproduction

```ts
type InferredCallback = (this: void) => void;

const TestObject: Record<string, InferredCallback> = {
	test() {

	}
}
```

**Expected behavior:**

The generated method should be a callback
```lua
-- Compiled with roblox-ts v1.1.1
local TestObject = {
	test = function() end,
}
return nil
```

**Current behavior:**

The generated function is a method, not a callback
```lua
-- Compiled with roblox-ts v1.1.1
local TestObject = {
	test = function(self) end,
}
return nil
```

## Playground link
[https://roblox-ts.com/playground/#code/C4TwDgpgBAkgdgMwgJ2RAJgYQIYBtcBG2AxgNZQC8UAFMABYCWAzgFxQBuA9g+gJSUA+Dt3QBuAFDjinOE2BQAKhDkB5AgCsIxYGwBKWzsnQAeOcgZwA5gBpYiFGix5CJUkKoBvcVB9Rgy4Gp+L29fAF9xMKA]().

**Comment by Dionysusnu** [comment]
better [playground example](https://roblox-ts.com/playground/#code/C4TwDgpgBAkgdgMwgJ2RAJgYQIYBtcBG2AxgNZQC8UAFMABYCWAzgFxQBuA9g+gDRQA6IdmQBzVlGxwQAbQC6ASkoA+Dt3QBuAFBbinOE2BQAKhEMB5AgCsIxYGwBKtzsnQAeQ8gZxR-eElQMHHwiMlUqAG8tKBioYDNgamw2OABXAFsCFCUo6NiAXy1CrVMLa1tgAXjDagBGBSA)
