### ISSUE TITLE
Transpile property/method accesses that would be invalid Lua into bracket syntax

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#136]
Solve the `promise:andThen` and `Symbol.for` macros in a more generic way, instead changing reserved Lua keyword accesses into bracket literal syntax.

`Symbol["for"]`
`promise["then"](promise, ...)` <-- need to do this special behavior for method syntax

Additionally when generating Lua from classes/otherwise, ensure that we do something like this:

```lua
t["then"] = function(self)
    
end
```

**Comment by osyrisrblx** [comment]
Method calls will be tricky..

Usually promises are done like..
`returnsAPromise().then(() =>{})`

we can't really compile that into:
`returnsAPromise()["then"](returnsAPromise(), function() end)`
because it could be two unique promise objects

**Comment by rlongre** [comment]
How about...

```lua
local returnsAPromise_1 = returnsAPromise()
returnsAPromise_1 = returnsAPromise_1["then"](returnsAPromise_1, function() end)
```

**Comment by GixxerK3** [comment]
How about...

```lua
local returnsAPromise_1 = returnsAPromise()
returnsAPromise_1 = returnsAPromise_1["then"](returnsAPromise_1, function() end)
```

**Comment by osyrisrblx** [comment]
Sure, we have precedent of doing something similar with generated variables elsewhere in the compiler (like `_0`)

But maybe allowing this is a bad idea to begin with:
Classes created with TS that use reserved Lua keywords would lose the ability to inter-op with Lua effectively.
But also, function calls can be expressions, so that could dramatically increase the complexity of compiled code.

For example, `foo(returnsAPromise().then(() => {}))`

**Comment by brianush1** [comment]
Why not introduce a method into RuntimeLib, e.g.
```lua
function TS.callMethod(obj, method, ...)
    return obj[method](method, ...)
end
```
`returnsAPromise().then(() => {})` would then compile into `TS.callMethod(returnsAPromise(), "then", function() end)`

**Comment by osyrisrblx** [comment]
I considered doing something like that or in-lining it to:
`(function() obj[method](obj, ...) end)(obj, method, args)`

However, this creates an extra function call on arbitrary methods. Probably a bad idea for performance.

**Comment by evaera** [comment]
We could only use that when dealing with a reserved keyword, right? I still agree with the problem about interop though

**Comment by brianush1** [comment]
Why not prepend a `__` to any reserved Lua keywords? That would make interop pretty simple and still allow the colon operator for calling.

**Comment by GixxerK3** [comment]
Still getting familiar with the code so I'm not sure how far your static analysis goes but maybe if not part of a chain of method calls, the transpiled function call could be prefixed:

```lua
local returnsAPromise_1 = returnsAPromise()
returnsAPromise_1 = returnsAPromise_1["then"](returnsAPromise_1, function() end)
foo(returnsAPromise_)
```

Especially since this would only really be necessary in the case of the use of reserved words.

**Comment by osyrisrblx** [comment]
@brianush1 it's not _great_ for interop but yes it would still work. However, we then have the issue of possible name collisions. What if I just happened to define a method on a class with `__` before it?

@GixxerK3 Yes, that could work, but an in-line function could work too. There's some examples of this in how we compile things like `x++`.

**Comment by GixxerK3** [comment]
@osyrisrblx True, but an IIFE would incur the same performance penalty as a function call from the runtime. Perhaps more actually.

**Comment by Validark** [comment]
In my view polluting the name of the method with a ton of underscores is going to be just as bad for interoperability. I think the best solution for renaming is going to be using CamelCase in Lua, as is standard for Roblox method names.

**Comment by evaera** [comment]
@Validark I think just capitalizing any Lua keywords when compiling to Lua is a good idea. `for` becomes `For`, etc. Not sure if you mean that it would do that for *all* names or just the keyword collisions, but I think it should be only the keyword collisions. As long as we document it, this seems like the best solution.

**Comment by Validark** [comment]
For Roblox-ts "built-in" names, I think **all**. For user created methods/variables/etc, just the keyword collisions.

**Comment by Validark** [comment]
In fact, I would like to see Roblox API and instance methods use lowerCase in TS and convert to PascalCase for Lua.

**Comment by Validark** [comment]
Actually I am thinking now it would be nice to have this be the default behavior for classes. You can write the API in TS in lowerCase and it will transpile to PascalCase Lua.

**Comment by osyrisrblx** [comment]
I do not like the idea of case conversion during transpiling. I think it just ends up making things very confusing for the end user.

However, I would be interested in switching to camelCase for rbx-types since that's more typescript-y. Unfortunately, that would break lemur support.
