### ISSUE TITLE
E404 Not Found - GET https://registry.npmjs.org/rbxtsc - Not found when trying to use NPX

### ISSUE THREAD

**Issue by acuaroo** [roblox-ts/roblox-ts#1371]
## Version

**roblox-ts:** Unknown, can't check because all rbxtsc commands do not work with any flags. Most likely most stable/latest, as I recently tried installing it.

**@rbxts/types:** Returns: 
```
└── (empty)
```

## Description
Currently, when trying to run `npx rbxtsc init`, I get the following error.
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/rbxtsc - Not found
npm ERR! 404 
npm ERR! 404  'rbxtsc@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## Minimal Reproduction
```bash
npm i rbxtsc

npx rbxtsc init
```

### **Expected behavior:**
The project should initialize with the source and out folders as-well as the `default-project.json`.

### **Current behavior:**
Every time I run any command using rbxtsc in npx, it returns a 404 error.

---

### **Extra info:**
OS: `macOS Catalina 10.15.7`
Complete Log: [Here](https://pastebin.com/nXBHQAdB)

---

**Comment by osyrisrblx** [comment]
npx uses the package name, not the CLI name. So you want to use `npx roblox-ts init`

**Comment by acuaroo** [comment]
Worked, thanks so I know for future reference
