### ISSUE TITLE
Undefined behavior with use of BindableEvents

### ISSUE THREAD

**Issue by headjoe3** [roblox-ts/roblox-ts#1398]
See: https://devforum.roblox.com/t/changes-to-lua-event-handling/1240569
As well as: https://devforum.roblox.com/t/changes-to-lua-event-handling/1240569/42?u=databrain

Currently there's only one use of BindableEvents in the Promise library:
https://github.com/roblox-ts/roblox-ts/blob/1e48f6218b7c04f1c938f2656574e7f722111438/lib/Promise.lua

![image](https://user-images.githubusercontent.com/4315566/119053881-f1972180-b983-11eb-8cbd-aa0e6b6139bc.png)

My workaround (for FastSpawn) uses BindableFunctions instead of BindableEvents.
```lua
--!strict

local FAST_SPAWN_BINDABLE = Instance.new('BindableFunction')
local FAST_SPAWN_CALLER = function(cb: () -> ())
	cb()
end :: any
local LOCK_IS_INVOKING = false
FAST_SPAWN_BINDABLE.OnInvoke = FAST_SPAWN_CALLER

local function FastSpawn(func: () -> ())
	if LOCK_IS_INVOKING then
		local nestedCallFastSpawnBindable = Instance.new('BindableFunction')
		nestedCallFastSpawnBindable.OnInvoke = FAST_SPAWN_CALLER
		coroutine.resume(
			coroutine.create(function()
				nestedCallFastSpawnBindable:Invoke(func)
			end)
		)
	else
		LOCK_IS_INVOKING = true
		coroutine.resume(
			coroutine.create(function()
				FAST_SPAWN_BINDABLE:Invoke(func)
			end)
		)
		LOCK_IS_INVOKING = false
	end
end

return FastSpawn
```

**Comment by osyrisrblx** [comment]
This should be fixed in [roblox-lua-promise](https://github.com/evaera/roblox-lua-promise) instead.

https://github.com/evaera/roblox-lua-promise/blob/master/lib/init.lua#L1103
