### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#140]
https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by osyrisrblx** [comment]
Closing this for now. Most of the use cases for decorators don't really apply to our environment.

**Comment by Kampfkarren** [comment]
@osyrisrblx Why the close instead of just leaving it open as "nice to have"? Are decorators not wanted period?

**Comment by Validark** [comment]
If someone submits a PR for decorators, it will be accepted if the implementation is correct.

I do believe there's also the issue of TS decorators vs ES decorators, and I'm not sure how that's going to play out.

**Comment by TheEdgyDev** [comment]
@Validark I would like to submit a PR for decorators excluding accessor decorators due to #457. 

I already have a 1-to-1 implementation for class decorators.

As for what constitutes a *correct* implementation for method and property decorators, what would you consider an acceptable and realistic implementation for PropertyDescriptor objects?

**Comment by Validark** [comment]
@TheEdgyDev The only law is the type checker, and decorators are up for negotiation. We intentionally don't support many JS features that we don't want and can just remove from our types and/or ban in our compiler. I don't know exactly what the use cases are or what someone would even want to do with property decorators. I can only say we don't want to impose decorator compatibility on code which doesn't use them. Feel free to write your own types that fit your use cases (if TS allows that, there should be a built-in `Decorator` type or something you could probably modify), and make a proposal. Obviously, it should be able to work with several use cases, like debouncing, perhaps memoizing, or whatever else you have in mind.
