### ISSUE TITLE
How can get LocalPlayer Humanoid

### ISSUE THREAD

**Issue by Raksix** [roblox-ts/roblox-ts#1426]
ref https://developer.roblox.com/en-us/api-reference/property/Humanoid/WalkSpeed

I try

```
import { Players } from "@rbxts/services";

const player = Players.LocalPlayer
const char = player.CharacterAdded.Wait()
const h = char.Humanoid

```

Humanoid undefined

Or

```
import { Players } from "@rbxts/services";

Players.LocalPlayer.CharacterAdded.Connect((player) => {
    const h = player.Humanoid
})
```

**Comment by Dionysusnu** [comment]
The best place to get help with roblox-ts _usage_ questions is in our [discord server](https://discord.gg/Sk6CkcXWnB)

**Comment by Raksix** [comment]
> The best place to get help with roblox-ts _usage_ questions is in our [discord server](https://discord.gg/Sk6CkcXWnB)

I can't verify my acc
