### ISSUE TITLE
Watch mode might be broken for WSL?

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1460]
Creating an issue to track this problem. Might be from #1424

**Comment by OverHash** [comment]
Using compiler built from commit hash 7edf5c512365e1a046ddecd747f610033f00edae onwards:
1) Open terminal
2) Run rbxtsc-dev --verbose --watch
3) Check emitted code, it should be like this for the comment:
```
--[[
    *
    * Does a funny thing..
]]
```
4) While in watch mode, edit src/getPetClickMultiplier.ts's comment by removing a . in the comment and saving the file
5) Watch the compiler emit, it will detect file changes but not actually recompile the file.
![image](https://user-images.githubusercontent.com/46231745/123374651-8cb29500-d5db-11eb-8b29-b1fd79606e79.png)

Minimal Repro file: [roblox-ts-file-issue.zip](https://github.com/roblox-ts/roblox-ts/files/6713755/roblox-ts-file-issue.zip)
