### ISSUE TITLE
Improper compilation of strings containing both apostrophes and quotation marks ending in a closing bracket

### ISSUE THREAD

**Issue by jheinem1** [roblox-ts/roblox-ts#1467]
## Version

**roblox-ts:** 1.1.1

**@rbxts/types:** 7.0.7

## Description
When a string containing both apostrophes and quotation marks is compiled, roblox-ts attempts to convert the string into a multiline string. However, roblox-ts fails to account for the edge case of a closing bracket at the end of the string, causing a syntax error in the resulting transpiled code.

## Minimal Reproduction
```TypeScript
let thing = `A string with a " and ' ending in a ]`;
```

**Expected behavior:**
```Lua
local thing = "A string with a \" and ' ending in a ]"
```

**Current behavior:**
```Lua
local thing = [[A string with a " and ' ending in a ]]]
```

## Playground link
[https://roblox-ts.com/playground/#code/DYUwLgBGAWCWB2BzCBeCADAghAzmATgsgO6wwQCGEARJfACYQDkEIDREClEAuugNxA](https://roblox-ts.com/playground/#code/DYUwLgBGAWCWB2BzCBeCADAghAzmATgsgO6wwQCGEARJfACYQDkEIDREClEAuugNxA).

**Comment by Dionysusnu** [comment]
> **roblox-ts:** 0.3.0

That's super outdated. Always make sure to update to the latest npm version before submitting an issue.

**Comment by Dionysusnu** [comment]
That said, this [does still happen](https://roblox-ts.com/playground_legacy/#code/DYUwLgBGAWCWB2BzCBeCADAghAzmATgsgO6wwQCGEARJfACYQDkEIDREClEAuugNxA) on latest github commit

**Comment by jheinem1** [comment]
> That's super

Sorry, forgot to update the version there, I was running roblox-ts v1.1.1 and @rbxts/types v7.0.7.
