### ISSUE TITLE
Lua escape pattern behaviour

### ISSUE THREAD

**Issue by Dionysusnu** [roblox-ts/roblox-ts#1476]
[discussed on discord](https://discord.com/channels/476080952636997633/494540040991539200/860888365712801822)

Currently, with [this code](https://roblox-ts.com/playground/#code/MYewdgzgLgBATgUwOYIB4wLwwEQB0Du2AsAFCiSyIqoBMmOuB2QA), and the native TS equivalent, the following things get printed:
string 1 in TS: "w"
string 1 in Lua: Errors with "invalid escape sequence"
string 2 in TS: "\w"
string 2 in Lua: "\w"

The first string erroring is quite counter-intuitive. However, copy-pasting a pattern from Lua into roblox-ts and getting different behaviour would also be. So, we have 3 options:
- preserve current behaviour, to not touch the backslashes at all
- always strip out backslashes (evaluate it like TS would) and re-add them for the necessary Lua characters
- Ban the first case with an error

**Comment by osyrisrblx** [comment]
> - preserve current behaviour, to not touch the backslashes at all

After thinking about this some, I think this is the best route. This seems more like an environment thing than a language/typechecking thing.
