### ISSUE TITLE
Compiler should detect multiple inputs mapping to the same output

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1494]
If a user defines `src/foo.ts` and `src/foo.lua`, both files will write to `out/foo.lua`.

We can't do much to "fix" this, but we should probably error in this case.

Incremental mode might make this tricky since we might not have access to all .ts input paths..

**Comment by Dionysusnu** [comment]
Basically duplicate of #1254, maybe close to avoid splitting discussion?

**Comment by osyrisrblx** [comment]
Agreed. Closing as a duplicate of #1254
