### ISSUE TITLE
Support Symbols

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#15]
`Symbol` is declared in roblox.d.ts to make the for-of loop work, but it should be fully supported. Currently, you can create a new Symbol but `Symbol` isn't defined in Lua. 

The `Symbol(name?: string)` constructor should return a userdata that is created with `newproxy(true)`, whose `__tostring` metamethod is overridden to return `Symbol(%s)` 

```lua
function Symbol (name)
	local symbol = newproxy(true)

	getmetatable(symbol).__tostring = function()
		return ("Symbol(%s)"):format(name or "")
	end

	return symbol
end
```

It would also be nice to support [Symbol.for](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for)

**Comment by osyrisrblx** [comment]
> It would also be nice to support Symbol.for
Due to `for` being a reserved keyword in Lua I'm not going to implement this for now.
