### ISSUE TITLE
If statement without operator on nested template literal will cause the call stack to overflow

### ISSUE THREAD

**Issue by xethlyx** [roblox-ts/roblox-ts#1527]
https://roblox-ts.com/playground/#code/MYewdgzgLgBATiEUDyAjAVgU2FAXDAbxjE2kwBMAVTAWwAcAbAQyk3wAM5UAPJiCTFACW5XAHoxAEgJgArjVSY4AX3YwAPjFlhymAGZCS5GMpgBeQsVKsqtRizZad+wxRMBuAFCeJMACIgpGAA5LAA7iBwANaeQnowABQISGhYOAB0JGS29MysAJSEnjAlMJ7K3r4A6pFREDAGJLHxSYgoGNhQmdYU1LkO5mYW2rqNFIUExaXllWIwNdH1Y82Jye1pXVk2ffasgxbBXLz8giLiYgCMwRNTJeVAA

I'm not sure why or how this occurs - very strange edge case I came across. This is fixed by simply making a comparison

**Comment by Dionysusnu** [comment]
The error occurs because of the string template type. It's trying to resolve it in some way, which results in infinite versions, because there are infinite numbers. Doing a comparison only masks the bug, because the typecheck that tries the resolving is triggered by the truthiness checks.

**Comment by osyrisrblx** [comment]
I'm guessing this is due to `isPossiblyTypeInner()` seeing an infinitely deep union/intersection type. Should be easy to fix, we just detect if it's a string template type and early out. Would also need to be fixed within `isDefinitelyTypeInner()`.
