### ISSUE TITLE
Question: Project setup for custom model

### ISSUE THREAD

**Issue by showenx** [roblox-ts/roblox-ts#1539]
Hi,
I'm new to Roblox-ts and trying to build  a custom model with design in (*.rbxmx) and typescript for the model logic.

I'm trying to follow this sample (https://github.com/roblox-ts/demo-model) with (dummy.rbxmx) file, I managed to build and import via Roblox studio.

``` json
"Workspace": {
      "$className": "Workspace",
      "$properties": {
        "FilteringEnabled": true
      },
      "Level": {
        "$path": "src/dummy.rbxmx"
      }
    }
```

The question I got is, for model I can only build and import from Roblox studio, is there any way to auto Sync from VSCode with Rojo connection?

And is there any Roblox-ts custom model project setup with a bit more details that I can follow?

thanks,
Shawn

**Comment by osyrisrblx** [comment]
You can accomplish this by doing `"$path": "./default.project.json"`
