### ISSUE TITLE
Do not allow identifiers with characters that aren't valid in Lua

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#173]
JS has a much more lenient set of rules for identifier names, allowing use of some non-alphanumerical characters. We should throw a TranspilerError if the user attempts to use these, in addition to providing a TSLint rule for them in #172

**Comment by Validark** [comment]
As far as I know the only difference is that JS allows dollar signs in variables and Lua does not. We could easily block dollar signs from identifiers.

**Comment by osyrisrblx** [comment]
https://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names

**Comment by evaera** [comment]
Bug after recent changes:

```ts
export const asdf = {
  scan: false
}
```

`Transpiler Error: Cannot use '_exports.scan' as identifier (doesn't match Lua's identifier rules)`

**Comment by evaera** [comment]
Fixed in 33e6fc2fa96a64d01b1aaa1c58132bc5bfe3754d
