### ISSUE TITLE
Functions of union types always compile to a "." call rather than a ":" call

### ISSUE THREAD

**Issue by headjoe3** [roblox-ts/roblox-ts#174]
I am not sure if this is intended behavior, but I have a custom "Connection" class, which mirrors RBXScriptConnection objects. 

In one of my classes, I have a union of RBXScriptConnections and Connections stored in an array
![image](https://user-images.githubusercontent.com/4315566/50741984-44604c00-11c2-11e9-98be-dc85ec45db1c.png)

And for garbage collection purposes, I have these connections disconnected when "Destroy()" is called
![image](https://user-images.githubusercontent.com/4315566/50741992-580bb280-11c2-11e9-86b9-1bd3a0fcfa90.png)

This compiles to the following:
![image](https://user-images.githubusercontent.com/4315566/50741996-6fe33680-11c2-11e9-8158-20d1b260ad7d.png)

When I separate the types, however, it compiles fine:
![image](https://user-images.githubusercontent.com/4315566/50742002-89847e00-11c2-11e9-8f03-26b378557c76.png)
![image](https://user-images.githubusercontent.com/4315566/50742005-92754f80-11c2-11e9-8196-4d30703d49a0.png)

Whether or not this is intended behavior is an interesting question. For one thing, the compiler takes no issue with this type of polymorphism, so I suspect the correct behavior would be to use a ":" call instead. But they also allow this
![image](https://user-images.githubusercontent.com/4315566/50742067-8b027600-11c3-11e9-8b3b-aa7228e7b5ab.png)

**Comment by osyrisrblx** [comment]
This is definitely a bug. I've been meaning to write some type inspection utility functions to better detect cases where things like this can be resolved.

And while we could totally just loop through the union type and make sure each function in the type is a method.. How do you resolve a union of A and B (`A | B`) where `A.foo()` is a method and `B.foo()` is not?

**Comment by Validark** [comment]
This is why I love Lua's separate `:` method syntax. The dot operator shouldn't sometimes implicitly pass a `this` and sometimes not. That's one thing Lua definitely got right in my opinion.

As far as solving this problem goes, I think your initial ideas are the right ideas. If someone tries to union types with the situation you described the developer should definitely see an error because that kind of code is begging to explode.

How would regular TS handle this? Arbitrarily pick one?

**Comment by evaera** [comment]
No, regular TS doesn't have any concept of methods vs non-methods. Everything is just a function.  In TS/JS, `this` is determined by call-site. 

`x.func()` -> `this` is `x` in the function
`const y = x.func; y()` -> `this` is undefined in the  function

**Comment by Validark** [comment]
Right. But in Lua you expect that behavior because you can't do `local y = x:func`. I just wish Lua's method syntax could have made it in to TS.

**Comment by Validark** [comment]
In TS the call site is ALWAYS passed into `this` (with it being undefined when you localize the function). To replicate this behavior, we could make everything a method call and implicitly pass a nil in for localized functions. 

Functions called from namespaces can be method calls. Everything can be a method call. The only other alternative would be to make a compiler error when types are unioned in that way.

**Comment by osyrisrblx** [comment]
Making things always a method would destroy Lua interop. We should resolve this based on types and error if union types disagree.

**Comment by osyrisrblx** [comment]
I don't think it's overly hyperbolic. A huge selling point of roblox-ts is being able to create type definitions for existing Lua code. i.e. rbx-roact. Your suggestion would break something as simple as Roact.createElement

**Comment by Validark** [comment]
I agree the transpiler should just error if union types disagree.
