### ISSUE TITLE
For loop iterator is not scoped to each iteration when compiled

### ISSUE THREAD

**Issue by headjoe3** [roblox-ts/roblox-ts#176]
Consider the following:
```
let callbacks: (() => number)[] = []
for (let i = 0; i < 10; i++) {
	callbacks.push(() => i)
}
callbacks.forEach(callback => {
	print(callback())
})
```

The expected behavior would be to print all of the numbers from 1 to 10

However, since for loops are compiled as while loops with "i" scoped over the whole while loop rather than for each iteration, you get the number "9" printed 10 times.

For loops should compile to this
![image](https://user-images.githubusercontent.com/4315566/50751961-51ecf480-1209-11e9-9cc4-9642657b8a8c.png)

Instead of this
![image](https://user-images.githubusercontent.com/4315566/50751980-603b1080-1209-11e9-98fc-94087fd6f9f7.png)

**Comment by Validark** [comment]
This is basically the difference between using var and let in a JS for loop. You got a point.
