### ISSUE TITLE
`$tuple()` macro

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1806]
https://typescripttolua.github.io/docs/advanced/language-extensions#multi

TypeScriptToLua has a contextual macro called `$multi` which compiles:
```TS
function myFunc(): LuaMultiReturn<[string, number]> {
  return $multi("foo", 4);
}

const [foo, four] = myFunc();
```

into
```Lua
function myFunc(self)
    return "foo", 4
end
foo, four = myFunc(nil)
```

We should add something similar! We could name this `$tuple()`.

**Comment by Dionysusnu** [comment]
This is basically the same as `["foo", 4] as LuaTuple<[string, number]>`. Just easier to write?
