### ISSUE TITLE
`$range()` macro

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1807]
JS numeric for loops are... complicated.

https://typescripttolua.github.io/docs/advanced/language-extensions#range-iterator-function

TypeScriptToLua has a contextual macro called `$range()` that compiles nicely into Lua numeric for loops.

We should add something similar!

**Comment by Dionysusnu** [comment]
This should be easy, since we already have a `forOfIterationType` util function, so detecting `$range` should be easy.
