### ISSUE TITLE
Convert existing macros to be prefixed with `$`

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1808]
Unfortunately, this would be a breaking change but I think it's important for the long term health of the compiler.

Currently we have four different types of macros:
1. Identifier Macros - `a`
2. Function Call Macros - `a()`
3. Property Function Call Macros - `a.b()`
4. Constructor Macros - `new a()`

These can be difficult to discover without looking at the docs and end up polluting the global namespace. In transformer plugins, we already have the tradition of prefixing macros with `$` because that is an invalid character for Luau identifiers.

I don't think it makes sense to do this for Property Function Call Macros and Constructor Macros.

Proposed changes:
```
Promise -> Promise
assert -> assert

PKG_VERSION -> $PKG_VERSION
typeOf -> $typeof
typeIs -> $typeIs
classIs -> $classIs
opcall -> $opcall
identity -> $identity
```

- `Promise` and `assert` remain the same.
- `typeOf` turns into `$typeof`. This macro was created because `typeof` is a reserved keyword in TypeScript. If we add the `$`, we do not need to capitalize the `o`.

Related:
#1806
#1807

**Comment by FNAFFree** [comment]
p

**Comment by Dionysusnu** [comment]
I don't think this makes sense for typeof. Much like assert, it's practically the same function in lua. I think the $ prefix should be used for things that will produce significantly different output.

**Comment by osyrisrblx** [comment]
> I don't think this makes sense for typeof. Much like assert, it's practically the same function in lua. I think the $ prefix should be used for things that will produce significantly different output.

The typeof macro needs to be different in _some_ way than just `typeof` to prevent the reserved keyword issue. Until now, that has been `typeOf` with the capitalized `o`. I think adding the `$` will be more consistent with the other macros _and_ allow us to get around that issue.

> Is Promise a macro? Or is that just Promise.then?
Both.

- `Promise` maps to `TS.Promise`
- `.then` maps to `.andThen`
Arguably, we could get rid of `Promise` being a macro and have the compiler emit `local Promise = TS.Promise` at the top of the file when the `Promise` identifier is used.

> Is ClassIs still necessary? I believe TypeScript narrows based on properties now. Otherwise, IsA on the top class should do?

In the past, we made it so `ClassName` was a union of strings, but this had a **huge** negative impact on compiler performance.

IsA is not always the correct answer, unfortunately. For example, the inheritance tree of `LocalScript` looks like:

`Instance > LuaSourceContainer > BaseScript > Script > LocalScript`

So if I want to know if something is a `Script`, but not a `LocalScript` I'd have to do:
`instance.IsA("Script") && !instance.IsA("LocalScript")`

Or simply, `classIs(instance, "Script")`

**Comment by Dionysusnu** [comment]
> The typeof macro needs to be different in _some_ way than just `typeof` to prevent the reserved keyword issue. Until now, that has been `typeOf` with the capitalized `o`. I think adding the `$` will be more consistent with the other macros _and_ allow us to get around that issue.

Then in that case, the same could be said for assert. I think it should be both or neither. And then why a breaking change? Everyone's used to the capitalisation already.

> * Arguably, we could get rid of `Promise` being a macro and have the compiler emit `local Promise = TS.Promise` at the top of the file when the `Promise` identifier is used.

Remember to ban it as a reserved identifier in this case, to avoid redeclaring?

> In the past, we made it so `ClassName` was a union of strings, but this had a **huge** negative impact on compiler performance.

But on specific classes, couldn't this be a single string? Would that be an issue? Maybe it wouldn't narrow anymore.
I see

> Instance > LuaSourceContainer > BaseScript > Script > LocalScript

That's cursed. But yeah we'll keep classIs in then as $classIs.
