### ISSUE TITLE
Feature request: Deno support

### ISSUE THREAD

**Issue by CertifiedRice** [roblox-ts/roblox-ts#1827]
Roblox-ts should be able to work with both Deno and NodeJS

**Comment by osyrisrblx** [comment]
The challenge here would be to get our existing dependencies that use NodeJS APIs to work with Deno. I'm not sure there's much to be gained by supporting Deno right now?

**Comment by CertifiedRice** [comment]
Deno is growing in popularity, and it is new. And some Node developers are starting to learn or even main Deno. Deno support will be great in the future.
