### ISSUE TITLE
Luau => TS

### ISSUE THREAD

**Issue by CertifiedRice** [roblox-ts/roblox-ts#1838]
A way to convert Roblox Lua into Roblox typescript with out rewriting all of the code in typescript

**Comment by osyrisrblx** [comment]
I agree this could be a useful tool, but I don't think it fits within the scope of this project. It should probably be its own project.

**Comment by Dionysusnu** [comment]
An example of that "own project" can be found at [Dionysusnu/lua-to-ts](https://github.com/Dionysusnu/lua-to-ts), although still WIP. (link posted with permission from Osyris)
