### ISSUE TITLE
UserInputService.GetMouseLocation()'s return type is Vector2 instead of Vector2 | undefined

### ISSUE THREAD

**Issue by vendkita** [roblox-ts/roblox-ts#1867]
`UserInputService.GetMouseLocation()` return type is set to Vector2 instead of Vector2 | undefined.

In Roblox's API, it states:
"If the location of the mouse pointer is offscreen or the players device does not have a mouse, the value returned will be undetermined instead of Vector2"

https://developer.roblox.com/en-us/api-reference/function/UserInputService/GetMouseLocation

**Comment by osyrisrblx** [comment]
Looks like this API will always return a `Vector2` value. In the event that the user doesn't have a mouse or the mouse is off screen, the API will return something like `Vector2(inf, inf)`, but not nil/undefined.
