### ISSUE TITLE
Compiling roblox-ts module results in if statement content to be turned into an array

### ISSUE THREAD

**Issue by alessandro-5-ilie** [roblox-ts/roblox-ts#1884]
Hello, while compiling my project I've noticed all of my if statements have been turned into an array conditional resulting in the module not working properly. A code example can be found down here, anyone able to tell me what's wrong with my config, or maybe pr and fix the issue with the compiler? 😞 

```ts
if (string.find(Command1, Commands.stop) {
     const Args = // not sharing rest of the code
}
```

compiles to 

```lua

if { string.find(Command1, Commands.stop) } then
       local Args = -- not sharing rest of the code
end
````

**Comment by Dionysusnu** [comment]
https://roblox-ts.com/docs/guides/lua-tuple
Not a bug.

**Comment by alessandro-5-ilie** [comment]
> 

Thanks and Thanks 🤣

**Comment by alessandro-5-ilie** [comment]
@Dionysusnu I tried in every way to utilize LuaTuples but I can't seem to solve this issue. Could you help me out?

**Comment by Dionysusnu** [comment]
We have a discord server for that. You should be able to find it in the readme or on the website.

**Comment by alessandro-5-ilie** [comment]
Thanks, I'll ask this there.
