### ISSUE TITLE
Compiler crashes with usage of namespace aliases (import K = X.Y.Z)

### ISSUE THREAD

**Issue by imkalrbx** [roblox-ts/roblox-ts#1895]
Compiler crashes with usage of namespace aliases (import K = X.Y.Z)
https://www.typescriptlang.org/docs/handbook/namespaces.html#aliases

Compiler crash message
![image](https://user-images.githubusercontent.com/91434778/161409797-04e19dd4-df1e-4d77-b8ad-85818df05d1d.png)

Use case:
Turning this
![image](https://user-images.githubusercontent.com/91434778/161409830-d9de72e8-c13f-4eb6-887d-6db090a8c6a1.png)

Into this
![image](https://user-images.githubusercontent.com/91434778/161409837-b36495f0-7aca-4c6d-a4fd-9760c7e8d5cb.png)

As suggested by Osyris on the Roblox TS discord server, const K = X.Y.Z is a working alternative (probably due to the nature of the transpiler? I don't know what I'm talking about here), but apparently isn't proper namespace aliasing.

**Comment by osyrisrblx** [comment]
Should probably compile to:
```TS
import K = X.Y.Z;
```
```Lua
local K = X.Y.Z
```
