### ISSUE TITLE
Programmatic API?

### ISSUE THREAD

**Issue by Unzor** [roblox-ts/roblox-ts#1927]
Hello,
I have a question: can you translate code programmatically? I need this for a project.
Thanks

**Comment by Dionysusnu** [comment]
Yes, that is precisely what roblox-ts does. However, you'll need to be more specific to get an accurate answer about what exactly you want to translate and how. This isn't really the place for it, though. You could start a discussion (GitHub feature), or ask in the discord server. It should be linked in the readme.
