### ISSUE TITLE
Why typescript?

### ISSUE THREAD

**Issue by Kinrany** [roblox-ts/roblox-ts#194]
Typescript is great, but wouldn't it be simpler to compile ~~the latest ecmascript~~ ES6 to roblox lua and then use the usual typescript compiler to generate JS?

**Comment by osyrisrblx** [comment]
TypeScript was chosen for two reasons:
- Regular JS does not have type information associated with it. It's unclear whether to compile `a + b` as `a + b` or `a .. b` since both strings and numbers use `+` in JS, but not in Lua. TypeScript allows us to understand what types of data the user is trying to manipulate.
- TypeScript's compiler does a lot of the job for us. The code for generating the TS AST is well documented / tested. All roblox-ts needs to do is traverse that AST and emit functionally similar structures.

**Comment by Kinrany** [comment]
Thinking about this again, `a + b` should be compiled as

```lua
add(a, b)

function add(a, b)
  if typeof(a) ~= 'string' and typeof(b) ~= 'string' then
    return a + b
  else
    return a .. b
end
```

**Comment by Kinrany** [comment]
Javascript's primary benefit over Lua is it's ecosystem.

Typescript provides a type system, but it's not sound and does not guarantee correctness.

This is less important as long as your code base is pure Typescript with no type assertions. But Typescript's type system is far from perfect, and it's impossible to fully cover with types any sufficiently large project. Sooner or later you'll run into `any`.

Interoperability with Typescript modules is a non-goal, but I bet people will expect it anyway.

**Comment by osyrisrblx** [comment]
> Typescript provides a type system, but it's not sound and does not guarantee correctness.

Sure, but this is a hell of a lot better than Lua. The goal here is to make Roblox games easier to make.

I'd argue it's unreasonable to expect us to support arbitrary modules from NPM since many could contain Node API usage.

**Comment by Kinrany** [comment]
I see. Yes, you're right and I'm wrong. Full interoperability with JS is way harder than just using existing syntax and infrastructure, and it still allows creating a new statically typed language that compiles to Lua. Which is truly great, thank you for doing this.

Given that it's impossible to maintain backwards compatibility in any way, I wonder if you have any plans to change the language?

**Comment by Validark** [comment]
Roblox-TS is its own language in some ways, but the purpose of the `TS` part of it is to piggyback off of Microsoft TypeScript's code linter and intellisense. While there are some changes we are making to our version of TypeScript, we can't change anything that would make those tools fail. For example, we can't decide to add a new syntax for Enums or make a new operator. That said, we have made some changes which can be found [here](https://roblox-ts.github.io/docs/behavior-changes) and [here](https://roblox-ts.github.io/docs/unsupported-features).

**Comment by Kinrany** [comment]
One thing you might be able to do relatively easily is to remove obsolete syntax.

My first candidates are import assignments `import x =` (`import x from` should be used instead) and angle bracket type assertions `a = <A>b` (`a = b as A` should be used instead).
