### ISSUE TITLE
Optimize destructuring variables/assignments on array literals

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1974]
When the RHS transforms into a `luau.Array`, this should be as simple as grabbing `node.members`.

```TS
let a = 1;
let b = 2;
// swap!
[a, b] = [b, a];
```
should compile into:
```Lua
local a = 1
local b = 2
-- swap!
local a, b = b, a
```
[playground link](https://roblox-ts.com/playground/#code/DYUwLgBAhhC8EEYDcAoUkBGcICZUHp8IBnAdygAcBCFAbSgBoIMBdbWjJqFpIA)

**Comment by osyrisrblx** [comment]
https://github.com/roblox-ts/roblox-ts/blob/master/src/TSTransformer/nodes/expressions/transformBinaryExpression.ts#L29-L101
https://github.com/roblox-ts/roblox-ts/blob/master/src/TSTransformer/nodes/statements/transformVariableStatement.ts#L94-L139
Two similar functions, one is for variable declarations and the other is for assignment expressions.
A few constraints on this optimization that I thought of:
- RHS needs to be an array literal.. maybe we should transform the RHS, see if it's a `luau.Array` and then unwrap it from there?
- RHS must be an "inline" array (cannot use `...x`)
- LHS must be a destructure
- Unsure if LHS can have default values? Probably safe.

**Comment by osyrisrblx** [comment]
Another constraint, optimization can't happen if any of the identifiers in a variable declaration are hoisted.

[playground example](https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABMOcAUBKRBvAUASAAcAnGMKNAQwwG5cBfXXCBAZykQG1KAaRAIz4QAuogC8XAIx8ATHwDMwukA)

**Comment by Dionysusnu** [comment]
That's a good one to point out is currently broken already with the LuaTuple functions:
https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABMOcAUBKRBvAUASAAcAnGMKNAQwwG5cBfXXUSWBRAE0wC5EAZEJQAqIQgBsApgB4A2mBABbAEYTiAGkQBnKKTABzDUtSTKYALoA+HAWISoIYkhkBGDQCJKbjTpASziSk1+QRFxaTlFFXUtHTIDRCM4E3MLBlwIBG1EGUpDDQh-AF5OTDogA
