### ISSUE TITLE
Error: Assertion Failed! Identifier and QualifiedName are not implemented for ImportEqualsDeclaration!   

### ISSUE THREAD

**Issue by HJWoods** [roblox-ts/roblox-ts#1989]
Not sure why this is happening - seems independent of any code I run - i.e i tried removing some of my code or entire classes to see if the problem would be resolved, but it isn't

**Comment by Fireboltofdeath** [comment]
The compiler doesn't currently support code like `import A = X.Y.Z` (see https://github.com/roblox-ts/roblox-ts/issues/1895) Some editors have a tendency to add these imports automatically so you should check at the top of your files.

**Comment by osyrisrblx** [comment]
Closing as duplicate of #1895
