### ISSUE TITLE
Support Roact Classes

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#20]
The compiler should support Roact as a first class citizen.

Right now, it's _really_ hard to write code with Roact using roblox-ts.

- Detect `class ClassName extends Roact.Component`, and compile it in a special way.
- Support JSX methods for Roblox GUI Instances

**Comment by Dog2puppy** [comment]
Any idea when this will be finished?

**Comment by Dog2puppy** [comment]
It’s currently one of the things preventing me from moving to roblox-ts for my game.

**Comment by Vorlias** [comment]
Added in commit https://github.com/roblox-ts/roblox-ts/commit/d21bb90c1352ea12c2791719da6235b3517cb636. 

Close @osyrisrblx  ?
