### ISSUE TITLE
Can roblox-ts be used to transpile TS to Lua for other platforms?

### ISSUE THREAD

**Issue by kthompson** [roblox-ts/roblox-ts#2048]
General question in the title. I am wondering if this same bit of software could be used for another game like Factorio for example that also uses Lua for game mods.

What would be involved in making this work for other platforms?

**Comment by osyrisrblx** [comment]
Unfortunately, Roblox's flavor of Lua has quite a few differences from vanilla Lua that would make this challenging. Instead, I recommend using this awesome project: https://typescripttolua.github.io/

**Comment by kthompson** [comment]
Awesome thanks 👍  very cool project btw 😄
