### ISSUE TITLE
Properly point to Typescript homepage

### ISSUE THREAD

**Issue by buoyantair** [roblox-ts/roblox-ts#21]
The link in the homepage that points to Typescript actually points to a non-specific page from the docs. Maybe it's better to point it to typescriptlang.org 's homepage. 

My 2 cents :)

**Comment by cntkillme** [comment]
Perhaps it'd be a better idea to issue this [here](https://github.com/roblox-ts/roblox-ts.github.io) as it relates to the site.

**Comment by evaera** [comment]
I had originally pointed to the TypeScript homepage, but I changed it to be the beginning of the Handbook instead. The only people that'd be clicking that link inquisitively are people who are unfamiliar with TypeScript, and TypeScript's homepage might be confusing to those people-- with JavaScript being the main focus. 

Even TypeScript's quick start guide and tutorials have the developer start out with using JavaScript before adding type information, which obviously can't work with this project and would be unfriendly to beginners.

So, the motivation behind linking to the beginning of the Handbook is that that is the only relevant part of the website to anyone concerned with roblox-ts.
