### ISSUE TITLE
Newly created .lua files are not registered as valid source files in watch mode

### ISSUE THREAD

**Issue by headjoe3** [roblox-ts/roblox-ts#211]
I get this error when new .lua files are created while the compiler is in watch mode. Restarting the compiler, it works fine.
![image](https://user-images.githubusercontent.com/4315566/52319378-94c7f680-2986-11e9-8115-d22f92b21ff5.png)

Related: #11 ?

**Comment by Validark** [comment]
Do those two have corresponding `.d.ts` files?

**Comment by headjoe3** [comment]
> Do those two have corresponding `.d.ts` files?

Only Popper.lua
