### ISSUE TITLE
CheckableTypes does not include Value types

### ISSUE THREAD

**Issue by daymxn** [roblox-ts/roblox-ts#2134]
Roblox defines an Instance called "Values", which has several sub-types. These include, but are not limited to:

- IntValue
- BoolValue
- CFrameValue
- NumberValue
- StringValue
- Vector3Value

Although, the `CheckableTypes` interface does not define these. This prevents you from doing checks like so:
```ts
typeIs(maybeItem, "IntValue")
```

**Comment by Fireboltofdeath** [comment]
`typeIs` is an alias for `typeof` (although it can compile to just `type`)

`typeof` is for getting the type of Roblox datatypes however it doesn't extend to sub-types of those datatypes, like the Value objects. `typeof(Vector3Value)` will just be `Instance`.

**Comment by Dionysusnu** [comment]
What you're actually looking for is probably `classIs(maybeItem, "IntValue")` or `maybeItem.IsA("IntValue")`

**Comment by daymxn** [comment]
> `typeIs` is an alias for `typeof` (although it can compile to just `type`)
> 
> `typeof` is for getting the type of Roblox datatypes however it doesn't extend to sub-types of those datatypes, like the Value objects. `typeof(Vector3Value)` will just be `Instance`.

> What you're actually looking for is probably `classIs(maybeItem, "IntValue")` or `maybeItem.IsA("IntValue")`

Ahh, I see. Yeah you're right- `classIs` seems to be what I'm looking for. Although, `classIs` doesn't seem to implicitly cast the value to the checked class. Is this expected behavior?

**Comment by Fireboltofdeath** [comment]
`classIs` is a type predicate, it has the same behavior as `typeIs`. I'm not sure what you mean by implicitly casting the value, if you're just checking the result in an if statement then it will narrow the input.

If you still need help, please join the [roblox-ts discord](https://discord.gg/Zspfx7RP4j) and ask in the help channel.
