### ISSUE TITLE
Incorrect usage of "self.x" when transitively referencing a static property of a class from another static property

### ISSUE THREAD

**Issue by HJWoods** [roblox-ts/roblox-ts#2137]
Sorry if I didn't word that very well, I'll try and explain a little better here.

As you can see here, I'm defining two static properties of a class. These values can and should be updated by a setter method elsewhere in the class, the 5 is just intended to be a placeholder value.
![image](https://user-images.githubusercontent.com/38426334/191402829-2568e4e6-36eb-4b7e-8c00-d9f2b65ab5ce.png)

I then have the "buffer" class which my root class has two instances of. The buffer class has a single constructor argument, which is a number. The buffers use the two static properties defined earlier.
![image](https://user-images.githubusercontent.com/38426334/191402975-6af3e5dc-92f2-454e-98bf-aa583ca0bbee.png)

As far as typescript is concerned, there is nothing wrong here. However when it is compiled to lua, we get this:
![image](https://user-images.githubusercontent.com/38426334/191403326-a5f2b674-8a2c-4f5c-8799-e7ffb5317e4f.png)
The compiler seems to believe that this statement is still within the scope of the "Controls" table, and thus uses a "self" argument, but this statement has been made outside the scope of the table or any functions attached to the table, and thus is being used globally.
This results in the following error:
![image](https://user-images.githubusercontent.com/38426334/191403506-76a274a6-d9be-4cdd-b79b-5f2184282b16.png)

**Comment by osyrisrblx** [comment]
Thanks, this is definitely a bug. As a workaround, you can simply do `Controls.pressDuration` to achieve the same behavior.

[Playground repro of bug](https://roblox-ts.com/playground/#code/MYGwhgzhAEAa0G8BQBICAXM6CWxoDMB7Q6AXmgCIjCKBuVDLXaAIzACczp0ALbCAHTV6AXyRA)

**Comment by HJWoods** [comment]
> As a workaround, you can simply do `Controls.pressDuration` to achieve the same behavior.

Good point, thanks

**Comment by osyrisrblx** [comment]
Looks like this feature was added in TypeScript 4.4, but was seemingly undocumented? Before that, referencing `this` in the initializer for a static class member resulted in an error.

TypeScript 4.4 _did_ add ["static class blocks"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#static-blocks-in-classes), but we also don't support this yet either. Hopefully soon!
