### ISSUE TITLE
Assertion error with false literal as left hand in binary expression in a Jsx Child Expression

### ISSUE THREAD

**Issue by Vorlias** [roblox-ts/roblox-ts#2139]
(Apologies for the crap issue title, I'm half asleep rn) 

Affects version `2.0.3`.

Basic reproduction:
```ts
import Roact from "@rbxts/roact";

<frame>
	{false && <frame/>} // problem is the `false` here. This throws the assertion error.
</frame>
```
Also seems to affect this case too:
```ts
import Roact from "@rbxts/roact";

const condition = false;

<frame>
	{condition && <frame/>} // problem is the `false` here. This throws the assertion error.
</frame>
```

When `true` is used instead of false, it compiles as per usual. Issue seems to be only with `false`. This is unfortunately an issue as some UI code may conditionally render based on things like `$NODE_ENV` (e.g. `$NODE_ENV !== "production"`) being a certain environment (which w/ env, will inline, such as in my case)

Playground link:
https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAWAChX2XUIA7C+GAKZ84AXjgAeLMhACAfKwCQAbwzIANhQFwAZNolSZVWQF9W4qgblA

**Comment by Dionysusnu** [comment]
Same issue as #2084 - the code doesn't cover all the allowed types.
TypeScript ignores the other part of `&&` when the left side is always `false`, so the type given to roblox-ts is also simply `false`.
