### ISSUE TITLE
Multiline templates compile incorrectly

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#215]
```TS
const x = `
a
b
c
`;
```
compiles to
```Lua
local x = "
a
b
c
";
```
which is invalid Lua code

**Comment by evaera** [comment]
You could escape the newlines:
```lua
"\
a\
b\
c\
"
```

**Comment by headjoe3** [comment]
Why would you not use 
```lua
local x = [[
a
b
c
]];
```
?

**Comment by evaera** [comment]
> Why would you not use
> 
> ```lua
> local x = [[
> a
> b
> c
> ]];
> ```
> 
> ?

Escape sequences are not recognized when using double square bracket string literals in Lua, so they are not the same as using double or single quotes. (There's also no way to escape a literal `]]` without using nested double square bracket literals, but then you could never support a literal `]=]`, so you'd have to keep adding more and more equals signs in hope no one ever tries to use that exact sequence. Just a bad time all around!)
