### ISSUE TITLE
File watching does not work in WSL

### ISSUE THREAD

**Issue by jheinem1** [roblox-ts/roblox-ts#2160]
`rbxtsc -w` does not detect file changes when run in WSL.

![image](https://user-images.githubusercontent.com/70541819/196062225-0dd0751c-f842-4fdc-8216-a7cdd68806b5.png)

...and to confirm that the file has actually been changed:

![image](https://user-images.githubusercontent.com/70541819/196062542-44ce8c0f-6acc-4db2-b1bd-90736a532f58.png)

`rbxtsc` does transpile properly when ran manually.

# Environment

![image](https://user-images.githubusercontent.com/70541819/196062300-65cf7a85-54e5-4cab-b9f0-edc023748ef1.png)

(should be noted that the project I have open is located in the *windows* file system, so `/mnt/C/users/USER/Desktop/Project`)

**Comment by jheinem1** [comment]
![image](https://user-images.githubusercontent.com/70541819/196062810-1a003a82-dcaf-4a99-8605-931b79783caf.png)

File changes do work when vscode (gui) is running inside Ubuntu, so this is exclusive to vscode-server (what runs inside WSL).

**Comment by OverHash** [comment]
Are you using WSL1 or WSL2?

**Comment by Dionysusnu** [comment]
For a workaround, you can use `rbxtsc -w --usePolling`.
As for a solution to the issue, I'm afraid this might just be a limitation of WSL with file watching back to the Windows fs?
Anyways, roblox-ts mostly just relies on `chokidar` to cover file watching ([link to code that calls chokidar](https://github.com/roblox-ts/roblox-ts/blob/e33cbbfac0cb6ee1dd76d4320b8ad52d2edb5e14/src/Project/functions/setupProjectWatchProgram.ts#L211)), so you might have more luck testing file watching with `chokidar` directly and opening an issue there if that still doesn't work.

**Comment by jheinem1** [comment]
> Are you using WSL1 or WSL2? edit: nevermind, Kernel states WSL2.

I'm using WSL2, yes.

**Comment by jheinem1** [comment]
> For a workaround, you can use `rbxtsc -w --usePolling`. As for a solution to the issue, I'm afraid this might just be a limitation of WSL with file watching back to the Windows fs? Anyways, roblox-ts mostly just relies on `chokidar` to cover file watching ([link to code that calls chokidar](https://github.com/roblox-ts/roblox-ts/blob/e33cbbfac0cb6ee1dd76d4320b8ad52d2edb5e14/src/Project/functions/setupProjectWatchProgram.ts#L211)), so you might have more luck testing file watching with `chokidar` directly and opening an issue there if that still doesn't work.

Will try that, thanks!

**Comment by jheinem1** [comment]
`rbxtsc -w --usePolling` resolves this issue, but I will look into `chokidar`'s implementation.

**Comment by jheinem1** [comment]
Oh and after moving the project to the WSL (2) file system (I put the project in `~`), file watching is fine so it probably has to do with how the windows file system is seen as a network/shared file system by Ubuntu.
