### ISSUE TITLE
Classes cannot be properly returned from remote functions.

### ISSUE THREAD

**Issue by BlueStaggo** [roblox-ts/roblox-ts#2176]
When a Lua table is returned from a remote function, it loses its metatable, and this also applies to Roblox-TS classes. However, can classes just get their metatable reassigned? I have tried casting it to unknown and back to the class and it would not work.

### module.ts
```typescript
export class Point {
	constructor(public x: number, public y: number) { }

	getLength() {
		return math.sqrt(this.x ** 2 + this.y ** 2);
	}
}
```
### main.server.ts
```typescript
import { Point } from "shared/module";

const myPoint = new Point(5, 3);
print(myPoint.getLength());
(game.GetService("ReplicatedStorage").WaitForChild("GetServerPoint") as RemoteFunction).OnServerInvoke = () => myPoint;
```
### main.client.ts
```typescript
import { Point } from "shared/module";

let point = (game.GetService("ReplicatedStorage").WaitForChild("GetServerPoint") as RemoteFunction).InvokeServer();
print(point); // { ["x"] = 5, ["y"] = 3 }

// point = setmetatable(point, Point as LuaMetatable<Point>);

// Without setting metatable: attempt to call a nil value
// With setting metatable: attempt to index nil with 'x'
print(point.getLength());
```

**Comment by Fireboltofdeath** [comment]
You have to serialize and deserialize the class to send it over the network. 

The best place to ask for help is [roblox-ts' discord](https://discord.com/invite/JFvZY5JSBT).

**Comment by BlueStaggo** [comment]
I just ended up making an extra "init" method for initializing the class. My class is just a wrapper for an instance, so I can easily construct the class with the instance and only call the init method if I am actually creating a new class. Also, the example I have given is flawed and I have fixed it. From fixing it, I found that out setmetatable is not working properly.
