### ISSUE TITLE
disable check for shared files importing server files

### ISSUE THREAD

**Issue by dvnelson72** [roblox-ts/roblox-ts#2187]
We started migrating from 1.3.3 to 2.0.x

The biggest issue we are having is that we have some shared classes that do inline imports based on RunService.IsServer()

A little pseudo code....

    private async GetModules() {
        if (RunService.IsServer()) {
            if (this._serverModule === undefined) {
                this._serverModule = await import('server/somemodule');
            }
        } else {
            if (this._clientModule === undefined) {
                this._clientModule = await import('shared/othermodule');
            }
        }
    }

I don't really want to refactor the code base around this.  I could, but it will add quite a bit of effort.

Is there some way to disable this check beyond forking?  It doesn't look like it in the code.

**Comment by Dionysusnu** [comment]
Check was added in #1899.
For some reason, I recall that this check wouldn't/shouldn't happen on `import()` as a function. But looking at the compiler source, it will. Maybe that was planned but forgotten about?
