### ISSUE TITLE
Improve output when accessing array index

### ISSUE THREAD

**Issue by sasial-dev** [roblox-ts/roblox-ts#2226]
Due to the conversion between 0 and 1 indexing, you may have to write TS code like `newState[action.id - 1]`. 
In luau, this is outputted as `newState[action.id - 1 + 1]`. This should be caught and rewritten to `newState[action.id]`

**Comment by Dionysusnu** [comment]
Yeah, this could be improved. Luckily, it'll be quite easy to change, as the logic is all inside the `offset` util. https://github.com/roblox-ts/roblox-ts/blob/6dfd8e6e54d254c564f9fe57869690175dbc97f0/src/TSTransformer/util/offset.ts#L15

**Comment by sasial-dev** [comment]
I've just come across this with again with better [repro](https://roblox-ts.com/playground/#code/CYUwxgNghgTiAEYD2A7AzgF3gByUiAXPJjAJYoDmA2gLoBQdy6WFIGASlCsEgLbwBeeAAoAlIIB8OPBCq8oGABYA6GFx69hARgA00-MrSkAXiDHiAtPC30gA)
