### ISSUE TITLE
error TS roblox-ts: MacroManager could not find symbol for Promise

### ISSUE THREAD

**Issue by ncoder** [roblox-ts/roblox-ts#2254]
I'm new to roblox-ts, I got this error. I see some evidence that promises are supported... 

```sh
error TS roblox-ts: MacroManager could not find symbol for Promise
You may need to update your @rbxts/compiler-types!
```

Any tips on how to resolve this? what can I check? (i wish it told me the file it failed on)

**Comment by Sabortoother708Luminary** [comment]
Do `npm install `in the terminal

**Comment by ncoder** [comment]
Thanks for the tip. 

I was trying to compile a _large_ codebase that was originally intended to run on a normal website.
I think my use case is simply out of scope for the intention of what roblox-ts tries to do.

I'll give it a go when i get a chance.
