### ISSUE TITLE
Compiler should error if it creates >200 variables in a Lua scope

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#23]
Because some variables are automatically generated for importing, destructuring, etc., we should track how many variables are generated in a given Lua scope and error if that number exceeds the Lua maximum of 200 per scope.

While there are hacks to get around this limit, the performance penalty makes it not worth it.

**Comment by TripleFrequency** [comment]
I assume you have looked at the possibility of storing (at least the content at the top of a file) in a table, instead. I can't of any detrimental performance concerns with that approach, but though I would offer the idea.

**Comment by osyrisrblx** [comment]
Closing this for now, I no longer think it's important to prioritize and any implementation would require a lot of refactoring with future feature additions.
