### ISSUE TITLE
Incorrect emit on `Array[number]?.()`

### ISSUE THREAD

**Issue by RigidStudios** [roblox-ts/roblox-ts#2347]
[Minimal repro here](https://roblox-ts.com/playground/#code/DYUwLgBAbgXBDeED2A7AoigJnAggJzwEMBPAHgAoBKCAXgD5okBLTBgX1oWXSzgG0AuhDYAoEaEgpOABgDcYqADpUGTHxQCA-IqrylKrOoG6gA)

Indexing an array of functions with a number followed by an optional chained call will not receive `+ 1` on the emitted index as it should.

**Comment by siriuslatte** [comment]
This appears to be ONLY happening within function invokes. Indexing object fields, methods, or anything else, doesn't seem to have this same behavior.

**Comment by osyrisrblx** [comment]
Fixed by #2475
