### ISSUE TITLE
Add --!nocheck comment in every compiled Luau files

### ISSUE THREAD

**Issue by Sakyce** [roblox-ts/roblox-ts#2441]
Some compiled Luau files may generate warnings in the output, especially the ones in rbxts_include:
![image](https://github.com/roblox-ts/roblox-ts/assets/55030860/6f4d38d9-52f6-4165-845b-6cdb91d1f80b)

I know that some rbxts_include files are manually written code (or even pre-compiled). But it's good to have an option to add a --!nocheck at the start of the file if it doesn't exist yet, regardless of if it's compiled or not.

Be careful if a comment directive already exists in the file, as it might throw a warning:
![image](https://github.com/roblox-ts/roblox-ts/assets/55030860/f36c5987-d568-4636-88df-e40c867ed399)

**Comment by Sakyce** [comment]
Update: [Roblox added a beta for native code generation and a comment directive is needed for it](https://devforum.roblox.com/t/luau-native-code-generation-preview-studio-beta/2572587).  There should have a way to be able to add native code directive easily in roblox-ts.
![image](https://github.com/roblox-ts/roblox-ts/assets/55030860/7b595eb1-e3ee-421a-bc37-23a08b1714f8)

**Comment by Dionysusnu** [comment]
Note: With #2465 both of these can at least be done manually.
