### ISSUE TITLE
Static Block Declarations

### ISSUE THREAD

**Issue by alberrttt** [roblox-ts/roblox-ts#2472]
```ts
class Foo {
	static Count = 0;

	static {
		this.Count++;
	}
}
```
(Yes, typescript allows static blocks to use `this`)
[playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQgFzNglsNMPAK4B220AvNAAwDc6mOehKzmG2AFvhADoSFbAGpRTLgF9UUoA)

The preferred output would be:
```lua
local Foo
do
	Foo = setmetatable({}, {
		__tostring = function()
			return "Foo"
		end,
	})
	Foo.__index = Foo
	function Foo.new(...)
		local self = setmetatable({}, Foo)
		return self:constructor(...) or self
	end
	function Foo:constructor()
	end
	Foo.Count = 0
	do
		Foo.Count += 1
	end
end
```

https://discord.com/channels/476080952636997633/1156033763965407252

**Comment by osyrisrblx** [comment]
Fixed by #2480
