### ISSUE TITLE
Generated Lua files should get a header comment

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#253]
At the top of every Lua file we generate, we could insert a comment at the very top. Practically speaking, it would be nice to have the date and time of compilation. If there was a message indicating that the code was transpiled from TypeScript, that might also help to prevent people from editing transpiled Lua.

**Comment by osyrisrblx** [comment]
I've been considering something like this:

```Lua
-- Generated with roblox-ts.github.io
-- [timestamp]

local TS = require(
	game:GetService("ReplicatedStorage")
		:WaitForChild("RobloxTS")
		:WaitForChild("Include")
		:WaitForChild("RuntimeLib")
);
-- ...
```

Feedback?

**Comment by Validark** [comment]
`Generated with` could probably be `Generated by`. I'm not sure about `roblox-ts.github.io`. It could be that, or Roblox-TS, or https://roblox-ts.github.io, with the last one allowing for users to alt+click in VSCode to go to the website.
