### ISSUE TITLE
MacroManager could not find symbol for Promise You may need to update your @rbxts/compiler-types!

### ISSUE THREAD

**Issue by Infraction7** [roblox-ts/roblox-ts#2536]
I was trying to compile open source rbxts game into Luau but seem i cant resolve this error^^^
rbxts project im trying to compile: [littensy/slither](https://github.com/littensy/slither)

**Comment by Infraction7** [comment]
any ideas how to resolve?

**Comment by Dionysusnu** [comment]
Can you show the output of `npm ls`?

**Comment by Infraction7** [comment]
`0 verbose cli H:\Allprograms\NodeJS\node.exe H:\Allprograms\NodeJS\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.4
2 info using node@v20.1.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:H:\Allprograms\NodeJS\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:H:\Rojo\slither\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Антон\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Антон\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 15ms
17 timing npm:load:configload Completed in 15ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm ls
21 verbose argv "ls"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 10ms
24 timing npm:load:display Completed in 12ms
25 verbose logfile logs-max:10 dir:C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_01_20_187Z-
26 verbose logfile C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_01_20_187Z-debug-0.log
27 timing npm:load:logFile Completed in 17ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 50ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 6 files
33 silly logfile done cleaning log files
34 timing command:ls Completed in 120ms
35 verbose stack Error: missing: @rbxts/bitbuffer2@^1.0.0-ts.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/compiler-types@^2.2.0-types.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/flipper@^2.0.1, required by slither@1.2.3
35 verbose stack missing: @rbxts/lapis@^0.2.4, required by slither@1.2.3
35 verbose stack missing: @rbxts/object-utils@^1.0.4, required by slither@1.2.3
35 verbose stack missing: @rbxts/pretty-react-hooks@^0.3.3, required by slither@1.2.3
35 verbose stack missing: @rbxts/react-reflex@^0.2.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/react-roblox@^0.2.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/reflex@^4.2.2, required by slither@1.2.3
35 verbose stack missing: @rbxts/remo@^1.2.3, required by slither@1.2.3
35 verbose stack missing: @rbxts/ripple@^0.7.1, required by slither@1.2.3
35 verbose stack missing: @rbxts/roact@npm:@rbxts/react-ts@latest, required by slither@1.2.3
35 verbose stack missing: @rbxts/services@^1.5.1, required by slither@1.2.3
35 verbose stack missing: @rbxts/set-timeout@^1.1.2, required by slither@1.2.3
35 verbose stack missing: @rbxts/t@^3.1.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/testez@^0.4.2-ts.0, required by slither@1.2.3
35 verbose stack missing: @rbxts/types@^1.0.729, required by slither@1.2.3
35 verbose stack missing: @rbxts/validate-tree@^2.0.2, required by slither@1.2.3
35 verbose stack missing: @typescript-eslint/eslint-plugin@^6.9.1, required by slither@1.2.3
35 verbose stack missing: @typescript-eslint/parser@^6.9.1, required by slither@1.2.3
35 verbose stack missing: cross-env@^7.0.3, required by slither@1.2.3
35 verbose stack missing: eslint-config-prettier@^9.0.0, required by slither@1.2.3
35 verbose stack missing: eslint-plugin-prettier@^5.0.1, required by slither@1.2.3
35 verbose stack missing: eslint-plugin-roblox-ts@^0.0.36, required by slither@1.2.3
35 verbose stack missing: eslint-plugin-simple-import-sort@^10.0.0, required by slither@1.2.3
35 verbose stack missing: eslint-plugin-unused-imports@^3.0.0, required by slither@1.2.3
35 verbose stack missing: eslint@^8.52.0, required by slither@1.2.3
35 verbose stack missing: prettier@^3.0.3, required by slither@1.2.3
35 verbose stack missing: rbxts-transform-debug@^2.2.0, required by slither@1.2.3
35 verbose stack missing: rbxts-transform-env@^2.2.0, required by slither@1.2.3
35 verbose stack missing: roblox-ts@^2.2.0, required by slither@1.2.3
35 verbose stack missing: typescript@^5.2.2, required by slither@1.2.3
35 verbose stack     at LS.exec (H:\Allprograms\NodeJS\node_modules\npm\lib\commands\ls.js:202:9)
35 verbose stack     at async module.exports (H:\Allprograms\NodeJS\node_modules\npm\lib\cli.js:89:5)
36 verbose cwd H:\Rojo\slither
37 verbose Windows_NT 10.0.19044
38 verbose node v20.1.0
39 verbose npm  v9.6.4
40 error code ELSPROBLEMS
41 error missing: @rbxts/bitbuffer2@^1.0.0-ts.0, required by slither@1.2.3
41 error missing: @rbxts/compiler-types@^2.2.0-types.0, required by slither@1.2.3
41 error missing: @rbxts/flipper@^2.0.1, required by slither@1.2.3
41 error missing: @rbxts/lapis@^0.2.4, required by slither@1.2.3
41 error missing: @rbxts/object-utils@^1.0.4, required by slither@1.2.3
41 error missing: @rbxts/pretty-react-hooks@^0.3.3, required by slither@1.2.3
41 error missing: @rbxts/react-reflex@^0.2.0, required by slither@1.2.3
41 error missing: @rbxts/react-roblox@^0.2.0, required by slither@1.2.3
41 error missing: @rbxts/reflex@^4.2.2, required by slither@1.2.3
41 error missing: @rbxts/remo@^1.2.3, required by slither@1.2.3
41 error missing: @rbxts/ripple@^0.7.1, required by slither@1.2.3
41 error missing: @rbxts/roact@npm:@rbxts/react-ts@latest, required by slither@1.2.3
41 error missing: @rbxts/services@^1.5.1, required by slither@1.2.3
41 error missing: @rbxts/set-timeout@^1.1.2, required by slither@1.2.3
41 error missing: @rbxts/t@^3.1.0, required by slither@1.2.3
41 error missing: @rbxts/testez@^0.4.2-ts.0, required by slither@1.2.3
41 error missing: @rbxts/types@^1.0.729, required by slither@1.2.3
41 error missing: @rbxts/validate-tree@^2.0.2, required by slither@1.2.3
41 error missing: @typescript-eslint/eslint-plugin@^6.9.1, required by slither@1.2.3
41 error missing: @typescript-eslint/parser@^6.9.1, required by slither@1.2.3
41 error missing: cross-env@^7.0.3, required by slither@1.2.3
41 error missing: eslint-config-prettier@^9.0.0, required by slither@1.2.3
41 error missing: eslint-plugin-prettier@^5.0.1, required by slither@1.2.3
41 error missing: eslint-plugin-roblox-ts@^0.0.36, required by slither@1.2.3
41 error missing: eslint-plugin-simple-import-sort@^10.0.0, required by slither@1.2.3
41 error missing: eslint-plugin-unused-imports@^3.0.0, required by slither@1.2.3
41 error missing: eslint@^8.52.0, required by slither@1.2.3
41 error missing: prettier@^3.0.3, required by slither@1.2.3
41 error missing: rbxts-transform-debug@^2.2.0, required by slither@1.2.3
41 error missing: rbxts-transform-env@^2.2.0, required by slither@1.2.3
41 error missing: roblox-ts@^2.2.0, required by slither@1.2.3
41 error missing: typescript@^5.2.2, required by slither@1.2.3
42 verbose exit 1
43 timing npm Completed in 608ms
44 verbose code 1
45 error A complete log of this run can be found in: C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_01_20_187Z-debug-0.log
`

**Comment by Dionysusnu** [comment]
Try using 3 backticks (```) on each side of the text, that'll put it in a full codeblock instead of an inline one.

**Comment by Infraction7** [comment]
![image](https://github.com/roblox-ts/roblox-ts/assets/112822467/9e8b4320-7af0-46b7-8237-683d023f60df)
![image](https://github.com/roblox-ts/roblox-ts/assets/112822467/c790bfc6-5f46-4739-8310-50a7ffee5e41)

**Comment by Dionysusnu** [comment]
Does your Visual Studio Code configuration hide your `node_modules` folder, or does it just not exist?
Try running `npm ci`.

**Comment by Infraction7** [comment]
`npm ci` returned an error:
```
0 verbose cli H:\Allprograms\NodeJS\node.exe H:\Allprograms\NodeJS\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.4
2 info using node@v20.1.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:H:\Allprograms\NodeJS\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:H:\Rojo\slither\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Антон\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Антон\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm ci
21 verbose argv "ci"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 3ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_07_19_162Z-
26 verbose logfile C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_07_19_162Z-debug-0.log
27 timing npm:load:logFile Completed in 13ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 34ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 verbose loadVirtual Error: loadVirtual requires existing shrinkwrap file
34 verbose loadVirtual     at Arborist.loadVirtual (H:\Allprograms\NodeJS\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-virtual.js:63:18)
34 verbose loadVirtual     at async CI.exec (H:\Allprograms\NodeJS\node_modules\npm\lib\commands\ci.js:34:5)
34 verbose loadVirtual     at async module.exports (H:\Allprograms\NodeJS\node_modules\npm\lib\cli.js:89:5)
35 timing command:ci Completed in 39ms
36 verbose stack Error: 
36 verbose stack The `npm ci` command can only install with an existing package-lock.json or
36 verbose stack npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
36 verbose stack later to generate a package-lock.json file, then try again.
36 verbose stack
36 verbose stack Clean install a project
36 verbose stack
36 verbose stack Usage:
36 verbose stack npm ci
36 verbose stack
36 verbose stack Options:
36 verbose stack [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
36 verbose stack [-E|--save-exact] [-g|--global]
36 verbose stack [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
36 verbose stack [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
36 verbose stack [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
36 verbose stack [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
36 verbose stack [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
36 verbose stack [-ws|--workspaces] [--include-workspace-root] [--install-links]
36 verbose stack
36 verbose stack aliases: clean-install, ic, install-clean, isntall-clean
36 verbose stack
36 verbose stack Run "npm help ci" for more info
36 verbose stack     at CI.usageError (H:\Allprograms\NodeJS\node_modules\npm\lib\base-command.js:101:26)
36 verbose stack     at H:\Allprograms\NodeJS\node_modules\npm\lib\commands\ci.js:40:18
36 verbose stack     at async CI.exec (H:\Allprograms\NodeJS\node_modules\npm\lib\commands\ci.js:34:5)
36 verbose stack     at async module.exports (H:\Allprograms\NodeJS\node_modules\npm\lib\cli.js:89:5)
37 verbose cwd H:\Rojo\slither
38 verbose Windows_NT 10.0.19044
39 verbose node v20.1.0
40 verbose npm  v9.6.4
41 error code EUSAGE
42 error
42 error The `npm ci` command can only install with an existing package-lock.json or
42 error npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
42 error later to generate a package-lock.json file, then try again.
42 error
42 error Clean install a project
42 error
42 error Usage:
42 error npm ci
42 error
42 error Options:
42 error [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
42 error [-E|--save-exact] [-g|--global]
42 error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
42 error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
42 error [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
42 error [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
42 error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
42 error [-ws|--workspaces] [--include-workspace-root] [--install-links]
42 error
42 error aliases: clean-install, ic, install-clean, isntall-clean
42 error
42 error Run "npm help ci" for more info
43 verbose exit 1
44 timing npm Completed in 1038ms
45 verbose code 1
46 error A complete log of this run can be found in: C:\Users\Антон\AppData\Local\npm-cache\_logs\2023-11-06T14_07_19_162Z-debug-0.log

```

**Comment by Dionysusnu** [comment]
Ah, I missed that slither uses yarn. Do you have `yarn` installed?
You should also run `npm uninstall -g roblox-ts`. (If you then encounter issues where roblox-ts is not found in other projects, run `npm i -D roblox-ts` in those)

**Comment by Infraction7** [comment]
I have yarn installed.

**Comment by Dionysusnu** [comment]
Try `yarn install --immutable --immutable-cache --check-cache`

**Comment by Infraction7** [comment]
I just fixed issue by adding node_modules thanks!
