### ISSUE TITLE
Indexing with strings tries to add 1

### ISSUE THREAD

**Issue by MojaveMF** [roblox-ts/roblox-ts#2545]
i tried to index with a string on an object with the any type (i was trying to figure out decorators since im new to them)

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
export default function test() {
	print("called first");
	return function (target: any, propertyKey: string) {
		print("Called", target[""]());
	};
}

```

```lua
local function test()
	print("called first")
	return function(target, propertyKey)
		print("Called", (target["" + 1]()))
	end
end
return {
	default = test,
}
````

**Comment by JakeyWasTaken** [comment]
just do "" - 1, easy!

**Comment by LovreDev** [comment]
You aren't supposed to use the `any` type in roblox-ts, it assumes target is an array. Defining a type for target which has the key defined as a string then it won't compile to that.

**Comment by OverHash** [comment]
See #1186 for more details (the release link is [here](https://github.com/roblox-ts/roblox-ts/releases/tag/v1.0.0-beta.5), originally broken in that post).

**Comment by LouieK22** [comment]
After a bit of digging, I figured out why this code would compile just fine:
```ts
function testCase(target: any) {
	return target["thing"]();
}
```

While this code would emit the correct diagnostic for using `any`:
```ts
function testCase(target: any) {
	return target["thing"];
}
```

The [`isAnyType` function](https://github.com/roblox-ts/roblox-ts/blob/master/src/TSTransformer/util/types.ts#L81-L83) will eventually get called on both of the identifiers at some point, but the `any` type object for example 1 is a different object than the `any` type object from example 2. The `isAnyType` function doesn't check the actual type flags of the type, it only checks an exact comparison with `state.typeChecker.getAnyType()`. 

The current recommendation that I could find in the documentations is to not rely on a comparison to the `getAnyType()` return value and instead check `Type.flags`. The change from flag checks to direct comparison was made in [this commit](https://github.com/roblox-ts/roblox-ts/commit/1c96174d56491ce1e1eb09d41e50583cb96f6082), so I am hesitant to immediately open a PR to switch back to the old implementation.
