### ISSUE TITLE
Failure to compile all files/folders while watching

### ISSUE THREAD

**Issue by Muoshuu** [roblox-ts/roblox-ts#255]
Getting some odd results when watching a directory, as seen here:

![36gueiqraz](https://user-images.githubusercontent.com/43345741/53286075-89b6e980-372e-11e9-8393-54d3b40fb5f8.gif)

Manually compiling works fine, issue only occurs when running `rbxtsc -w`

[project-folder.zip](https://github.com/roblox-ts/roblox-ts/files/2896759/project-folder.zip)

**Comment by osyrisrblx** [comment]
This should be fixed in 0.0.30. Let me know if you continue to have problems and I can reopen this issue.

**Comment by Muoshuu** [comment]
Reproduced on a second machine by following the steps in [the quick start guide](https://roblox-ts.github.io/docs/quick-start). Version is 0.0.30. Same results on latest and LTS NodeJS. Attempted via Windows Subsystem for Linux (Ubuntu) & directly in Windows.

**Comment by grubsteak** [comment]
[this doesn't seem to check for a root/<baseName>/index.ts](https://github.com/roblox-ts/roblox-ts/blob/0c6b4e58a9c65df17df17d73198de4f4dfc5961b/src/Project.ts#L350).
