### ISSUE TITLE
plugins arnt working

### ISSUE THREAD

**Issue by AshtonK5** [roblox-ts/roblox-ts#2570]
npx rbxtsc init plugin
npx rbxtsc build 

And then I get a compiler types update error and I update it and the error still doesn't go away 
**( and doesn't provide a build output it doesn't build the project )**

but when I do the same steps on making a new 'game' project it works but still gives me the compiler types error 
**( and provides an output to the output folder )**

**( I ALSO REINSTALLED ROBLOX TS FROM NPM AND THAT DIDNT FIX ANY ISSUES **)

**Comment by Dionysusnu** [comment]
Try running `npm uninstall -g roblox-ts`, and then use `npm init roblox-ts` to create a new project.
