### ISSUE TITLE
Unknown expression: ExpressionWithTypeArguments

### ISSUE THREAD

**Issue by corporatte-dev** [roblox-ts/roblox-ts#2581]
I recently has imported a Hitbox Raycast typing module when trying to compile my changes I have received this compiling error:

`Error: Assertion Failed! Unknown expression: ExpressionWithTypeArguments`

The errors seemed to have stemmed through here:
`at assert (C:\Projects\alterwind-framework\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)`

`at transform Expression(C:\Projects\alterwindframework\node_modules\robloxts\out\TSTransformer\nodes\expressions\transformExpression.js:98:25)`

**Comment by Dionysusnu** [comment]
This was fixed by #2446. Your version of roblox-ts is outdated.

**Comment by corporatte-dev** [comment]
Gotcha, thank you!

**Comment by LLethul** [comment]
Please close the issue
