### ISSUE TITLE
Spread operator on objects do not compile correctly

### ISSUE THREAD

**Issue by simondoesstuff** [roblox-ts/roblox-ts#2592]
Example use case where this feature would be useful. This provides a wrapper around a base interface, providing extra extension properties. The TS compiler does not complain and compiles successfully, but produces invalid luau code.

Input TS:
```ts
export function XPlayer(player: Player) {
	return {
		... player,
		Humanoid: player.Character?.FindFirstChild("Humanoid") as Humanoid,
	};
}
```

Generated Luau:
```lua
-- Compiled with roblox-ts v2.2.0
local function XPlayer(player)
	local _object = {}
	for _k, _v in player do
		_object[_k] = _v
	end
	local _left = "Humanoid"
	local _result = player.Character
	if _result ~= nil then
		_result = _result:FindFirstChild("Humanoid")
	end
	_object[_left] = _result
	return _object
end
return {
	XPlayer = XPlayer,
}
```

Error:
`attempt to iterate over a Instance value`

**Comment by Fireboltofdeath** [comment]
The spread operator is only for objects, it won't work on datatypes.

At most, roblox-ts could provide a diagnostic when you try to spread these types.

**Comment by simondoesstuff** [comment]
> The spread operator is only for objects, it won't work on datatypes.
> 
> At most, roblox-ts could provide a diagnostic when you try to spread these types.

The spread operator **is** used on an object. Am I missing something?
I'm taking in an (object) instance of the Player (datatype) and composing a new object using its properties. The typescript compiler does not complain -- it is valid functionality.

**Comment by Fireboltofdeath** [comment]
Players are not objects. TypeScript doesn't complain because in JS, everything is an object. That is not the case for Luau, and this would not be valid nor possible in Luau.

**Comment by simondoesstuff** [comment]
I see. It might be viable if luau supported the iteration of class members, but until then...
