### ISSUE TITLE
Bug: can't get string length

### ISSUE THREAD

**Issue by test3211234** [roblox-ts/roblox-ts#2602]
Cannot access string's length by "(stringvar).length" or "#stringvar" or "string.len((stringvar))" or "string.len()". Error: "Property 'length/len' does not exist on type 'string'." I'm pretty sure you would intend us to use string.len but len is the only thing missing on string.

I'm trying to turn a string into a byte array, if there's a better way than creating a table, looping through the strings size and pushing the string.byte of each index into the table then please let me know.

**Comment by Dionysusnu** [comment]
Not a bug. Use `.size()`. Roblox-ts does not intend to fully replicate JS apis.

**Comment by test3211234** [comment]
I just found this, I'm sorry for not looking before. Also I was going to ask why just ".size" wasn't working but ".size()" does work so thanks.
