### ISSUE TITLE
Add support for private methods in classes.

### ISSUE THREAD

**Issue by tannnxr** [roblox-ts/roblox-ts#2637]
I was trying to create a couple of private methods in my class.  However it seems that roblox-ts does not have support for that and just connects the functions to the meta-table.

Repro:

```ts
class MyClass {
    private secretMethod() {}
    publicMethod() {}
}
```

Which generates:
```
local MyClass
do
	MyClass = setmetatable({}, {
		__tostring = function()
			return "MyClass"
		end,
	})
	MyClass.__index = MyClass
	function MyClass.new(...)
		local self = setmetatable({}, MyClass)
		return self:constructor(...) or self
	end
	function MyClass:constructor()
	end
	function MyClass:secretMethod()
	end
	function MyClass:publicMethod()
	end
end
```

You can see it's not generating actual private methods. I can still use these methods.  It is important to have private methods automatically generated when I do it like this for organization sake.  If someone could please fix/add this feature.

**Comment by Fireboltofdeath** [comment]
This is behaving as it should.

The `private` keyword is purely type-based privacy, it doesn't have an effect on runtime behavior. It sounds like you want private identifiers, which is a separate feature and has been brought up before and I believe the decision was that it was too complicated to implement and for no real gain.
