### ISSUE TITLE
Iteration type not implemented: any

### ISSUE THREAD

**Issue by sunkenball** [roblox-ts/roblox-ts#2650]
`export const fire = (name: string, ...args: any) => {
	const event = getEvent(name);
	assert(event, `${event} does not exist`);
	event.FireServer(...args);
};
`

breaks on the event.FireServer(...args); line

**Comment by sasial-dev** [comment]
`any` is not supported in roblox-ts. Use `unknown` or `never` instead depending on your usecase.
