### ISSUE TITLE
An unexpected index increment occurred when access a field via index signature by string.

### ISSUE THREAD

**Issue by zyilet** [roblox-ts/roblox-ts#2674]
In typescript : 
``` typescript
function foo(goo: object) {
    const value = (goo as any)["field"]
}

```
In lua:
``` lua
local function foo(goo)
	local value = goo["field" + 1]
end
```

**Comment by Tesmi-Develop** [comment]
How were you able to compile this code when you cast in any?
https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABMOcAUBzVAuRcBGAVgKbQCUiA3gLABQiDiECAzlIgG4CGANiMYgC8iTKkRcW4sAE8yAbQBEwGMR4ATBQF06AXyA

> In typescript :
> 
> ```ts
> function foo(goo: object) {
>     const value = (goo as any)["field"]
> }
> ```
> 
> In lua:
> 
> ```lua
> local function foo(goo)
> 	local value = goo["field" + 1]
> end
> ```

**Comment by Dionysusnu** [comment]
Your compiler is outdated.
Run `npm uninstall -g roblox-ts` and `npm i -D roblox-ts@latest`

**Comment by zyilet** [comment]
> How were you able to compile this code when you cast in any? https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABMOcAUBzVAuRcBGAVgKbQCUiA3gLABQiDiECAzlIgG4CGANiMYgC8iTKkRcW4sAE8yAbQBEwGMR4ATBQF06AXyA
> 
> > In typescript :
> > ```ts
> > function foo(goo: object) {
> >     const value = (goo as any)["field"]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In lua:
> > ```lua
> > local function foo(goo)
> > 	local value = goo["field" + 1]
> > end
> > ```

I'm not using the latest version
