### ISSUE TITLE
Using the super keyword calls the super class statically, instead of calling the super instance

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#27]
If you have an inheriting class that references members of the super class instance explicitly, then the compiled Lua attempts to reference the super class statically, which is not correct.

Simple enough to reproduce, just have a class inherit from another, then try to use the `super` keyword to reference something from the super class instance.

TypeScript class calling the super instance:
```TypeScript
class SuperTest {
    superText: string = "Test"
}

class Test extends SuperTest {
    text: string = super.superText
}
```
Compiled Lua where calls to the super instance are instead referencing static values inside the super class:
```Lua
SuperTest = (function(super)
	local _0 = setmetatable({}, super);
	_0.__index = _0;
	_0.new = function(...)
		local self = setmetatable({}, _0);
		self:constructor(...);
		return self;
	end;
	_0.constructor = function(self, ...)
		if super then super.constructor(self, ...) end;
		self.superText = "Test";
	end;
	return _0;
end)();
Test = (function(super)
	local _0 = setmetatable({}, super);
	_0.__index = _0;
	_0.new = function(...)
		local self = setmetatable({}, _0);
		self:constructor(...);
		return self;
	end;
	_0.constructor = function(self, ...)
		if super then super.constructor(self, ...) end;
		self.text = SuperTest.superText;
	end;
	return _0;
end)(SuperTest);
```

**Comment by osyrisrblx** [comment]
Hmm I think it should probably be:
`self.text = self.superText;`

Need to detect whether references to fields are static or not
