### ISSUE TITLE
Generated Lua files without header

### ISSUE THREAD

**Issue by zaoqi** [roblox-ts/roblox-ts#270]
I want to use my own minimum runtime, not
```lua
local TS = require(
	game:GetService("ReplicatedStorage")
		:WaitForChild("RobloxTS")
		:WaitForChild("Include")
		:WaitForChild("RuntimeLib")
);
```

**Comment by TrafficConeGod** [comment]
They are planning on removing the runtime lib anyway.

**Comment by Validark** [comment]
If you use functions from the runtime-library, it will automatically import it into the top of your script. In the future, the runtime library could only include the functions you use, but for now, it is the way it is.

**Comment by osyrisrblx** [comment]
Closing this until more info is given.

I'm not really sure what you mean by "minimum runtime".

The compiler expects you to have certain functions in the runtime library.
If it attempts to use functions that are missing then your code would error.
