### ISSUE TITLE
Missing hoist: Nested class definitions

### ISSUE THREAD

**Issue by Dionysusnu** [roblox-ts/roblox-ts#2718]
[Repro](https://roblox-ts.com/playground/#code/MYGwhgzhAECC0G8CwAoAkBALmTBLY0AtgKaEBGxATtALzSiQwBCiqaaJmAFgPYAmACgCUrdO0rFMAV0oA7aLOIB3OMIDcbNAF82WjSh0ogA)
```ts
class A {
	static member = class B {
		method() {
			return new A();
		}
	};
}
```
A should be hoisted for `B.method` to access it, but it isn't.

**Comment by osyrisrblx** [comment]
Two reasons this happens:

1. Classes are exempted from hoisting [here](https://github.com/roblox-ts/roblox-ts/blob/ca58da367d99ca12072906ad2d49baa3ea811755/src/TSTransformer/nodes/expressions/transformIdentifier.ts#L59-L62) for internal self references. This is assumption is based on our current class code gen that does a `local class` at the top. I think this is fine.

2. When transforming class members, we don't do anything special with prereqs. This means they are handled in `transformStatement()` for the class itself.

Here's a very simple [example](https://roblox-ts.com/playground/#code/DYUwLgBAHhC8EAYDcAoAxsAhgZ2xAGhAN4oCQ2YmYAlmhAG6bACuIc0A1B6gL5A). This works, but I think it's needlessly confusing.

Maybe the prepreqs could just go right before the member assignment statement? (`X.value = _original` in that example)

I don't see any reason why we couldn't do this, but we'd have to be very careful to grab every sort of `transformX()` within the class transform procedure.
