### ISSUE TITLE
Running `pnpm run watch` throws an error

### ISSUE THREAD

**Issue by SatiXXGG** [roblox-ts/roblox-ts#2758]
This appeared suddenly, I don't have any type errors in my code and it seems to be an internal error of the compiler itself.

![image](https://github.com/user-attachments/assets/6ef34521-8c14-4c72-a996-ce3f7e5939f2)

**Comment by Dionysusnu** [comment]
Are you by any chance referencing `import.meta` somewhere in your code? Roblox-ts doesn't support that. (In fact, I wasn't even aware it was a thing before seeing this error)

**Comment by SatiXXGG** [comment]
> Are you by any chance referencing `import.meta` somewhere in your code? Roblox-ts doesn't support that. (In fact, I wasn't even aware it was a thing before seeing this error)

Apparently yes, I hadn't realized it, I had no idea I couldn't stand it 😥

This was the thing that broke everything:

```
if (new.target === settingController) {
	error("Cannot construct SettingController instances directly");
}
```
