### ISSUE TITLE
math.random wrongfully expects parameters to not be nil

### ISSUE THREAD

**Issue by abidbmt** [roblox-ts/roblox-ts#2774]
math.random in luau has optional parameters, but it doesnt seem so in rbx-ts. The below pictures show the emit in roblox studio and in vs-code where in roblox studio, there isnt any issues but in vs-code, im getting an error

Luau:
![image](https://github.com/user-attachments/assets/42ac739f-480a-4309-8523-32a920ff80cc)

rbx-ts:
![image](https://github.com/user-attachments/assets/46f12184-c03a-4b9f-9b46-d34855e15388)

**Comment by Dionysusnu** [comment]
This is actually correct; The luau types aren't fully accurate. While you can call `math.random` with less than 2 arguments, if an argument _is_ passed, then it must be a number. `nil` will cause an error.
You can try this snippet in the [Luau demo](https://luau.org/demo):
```lua
function a(p1, p2)
	math.random(p1, p2)
end

a(1, nil)
```
And you'll get:
```
Error:2: invalid argument #2 to 'random' (number expected, got nil)
```
