### ISSUE TITLE
Using Instances causes extremely long compile times

### ISSUE THREAD

**Issue by vocksel** [roblox-ts/roblox-ts#281]
I just rewrote a function for getting all descendants of a class, and compiling just got extremely slow

```typescript
export const getDescendantsOfClass = <C extends keyof Instances>(
    parent: Instance,
    className: C
): Instances[C][] =>
    parent.GetDescendants().filter((d): d is Instances[C] => d.IsA(className))
```

Saving the file without this function results in the usual ~300ms compile time. With it, I'm getting upwards of 20,000ms.

I'm guessing it has to do with the Instances lookup that I got from rbx-types (copied the FindFirstChildOfClass definition essentially)

**Comment by Validark** [comment]
By the way, a function named getDescendantsOfClass should in my view check `d.ClassName === className` and checking `IsA` would be more in-line with the functions named `WhichIsA` so your function could be named `getDescendantsWhichAre`.

To address the actual issue, I do not believe that this is in our hands. I welcome Osyris to test this if it is possible to, but I don't think our transpiler would care about indexing Instances. From the transpiler's perspective, you are defining a function which should be exported called getDescendantsOfClass, which has two parameters named `parent` and `className`, and returns the results of a simple filter function. The return type doesn't matter to us, the `d is Instances[C]` doesn't matter to us, and the types of the parameters do not matter either. The template is irrelevant to the transpiler as well. I changed the function a bit and I did indeed get different levels of performance when I made the types simpler. But this wouldn't have anything to do with the transpiler; hence you can dumb down the types and it will compile to the same Lua, even though it makes a difference in how long it takes to transpile.

To support my theory: this transpiles ~2 times faster (although the types are less useful) to the same exact Lua:
```ts
export const getDescendantsOfClass = (parent: Instance, className: string): Array<Instances[keyof Instances]> =>
	parent.GetDescendants().filter(d => d.ClassName === className);
```
```lua
local getDescendantsOfClass = function(parent, className)
	return TS.array_filter(parent:GetDescendants(), function(d)
		return d.ClassName == className;
	end);
end;
```

Interestingly enough, when using my [rbx-safe-types](https://www.npmjs.com/package/rbx-safe-types) (my drop-in replacement for rbx-types), I can compile your original code over 25 times faster than when using rbx-types.

**Comment by Validark** [comment]
With the introduction of this PR, https://github.com/roblox-ts/rbx-types/pull/66, your code now compiles at least 7 times faster on my machine after updating. I believe this issue can now be closed.
