### ISSUE TITLE
UniqueId missing in Instance type

### ISSUE THREAD

**Issue by dev-syn** [roblox-ts/roblox-ts#2833]
I'm trying to access an Instances UniqueId property and roblox-ts doesn't have it.

[Instance.UniqueId](https://create.roblox.com/docs/reference/engine/classes/Instance#UniqueId)

Roblox does show that UniqueId does exist inside the Instance class.

**Comment by wad4444** [comment]
`Instance.UniqueId` is a property exclusive to roblox studio, you cannot interact with it via scripts. Indexation results in a runtime error.

**Comment by dev-syn** [comment]
> `Instance.UniqueId` is a property exclusive to roblox studio, you cannot interact with it via scripts. Indexation results in a runtime error.

Ah okay, didn't know that thanks. I was wondering if I could use these ID's for my own purpose for a plugin. I'll close this now
