### ISSUE TITLE
Strings arn't working

### ISSUE THREAD

**Issue by AshtonK5** [roblox-ts/roblox-ts#2842]
So when I use something like if (string.match("str", "str") !== undefined) {

}

It compiled down to

if { string.match("str", "str") ~= nil }

end

And wrap it into an object for some reason ??

And break its functionality

**Comment by christopher-buss** [comment]
string.match returns a LuaTuple, so you have to access the first index.

https://roblox-ts.com/playground/#code/JYMwBAFAzgLgTsAdgcwHQFsCGMDGALCAIljkIBoxj5CBKAbQAYBdMAQgF52wBXRAEwCmIJAL40wAbwBQUgL5A
