### ISSUE TITLE
Bug: for-in loop statements are not supported!

### ISSUE THREAD

**Issue by AshtonK5** [roblox-ts/roblox-ts#2848]
### **Im working with objects and they don't really have any .forEach() method on them so I don't know how to iterate over them?**

```
     /* Internal Call Only! */
     private map(): MappedStyleProps_t {
          const mappedStyles: MappedStyleProps_t = { };
          

>            for (const key in this.unmappedStyles) {
>                const unmappedStyle = this.unmappedStyles[key];
>                if (unmappedStyle) {
>                     
>                     // Use getMappedStylesToProps to map and assign to mappedStyles
>                     mappedStyles[key] = getMappedStylesToProps(unmappedStyle) as MappedStyleProps_t;
>                }
>           }

          
          return mappedStyles;
     }
```

**Comment by Velover** [comment]
what you prob looking for is 
for-of loop

at the worst you prob looking for
```ts
for(const [key, value] of pairs(object_value)){}
```

**Comment by Velover** [comment]
could you try asking in the help channel?
if the compiler gives you an error it's prob not an issue with it 90% of the time I think

and in the help channel the people maybe gonna help faster than is git issues

**Comment by AshtonK5** [comment]
> could you try asking in the help channel? if the compiler gives you an error it's prob not an issue with it 90% of the time I think
> 
> and in the help channel the people maybe gonna help faster than is git issues

Yea sry mb I'm also just really knew to typescript and git and everything, but do you know any help channels that use roblox-ts?

**Comment by Frostelth** [comment]
> Yea sry mb I'm also just really knew to typescript and git and everything, but do you know any help channels that use roblox-ts?

there's a help channel in the roblox-ts discord https://discord.com/invite/JFvZY5JSBT
