### ISSUE TITLE
the "while" part of do-while loops should not share scope with the inner-block

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#292]
![image](https://user-images.githubusercontent.com/9200592/54838489-178ae380-4c9f-11e9-9de6-93f7fb2d23f4.png)

**Comment by Validark** [comment]
Good point. I knew that scoping was handled differently between TS-Lua in this case but I didn't think of how it *could* lead to the wrong code being outputted.
