### ISSUE TITLE
We should error if tsconfig.json isn't UTF-8

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#296]

**Comment by osyrisrblx** [comment]
Maybe rojo.json too?

**Comment by Validark** [comment]
Why does non UTF-8 make it fail?

**Comment by osyrisrblx** [comment]
Not sure, seems to break the TypeScript compiler itself. Gets weird errors in what looks like JSON decoding?

**Comment by Validark** [comment]
It doesn't hurt my feelings that we don't support it, I am just curious why it matters. Strange.
