### ISSUE TITLE
Support third party framework import statements

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#3]
In frameworks like [RoStrap](https://rostrap.github.io/Resources/), there is a custom "LoadLibrary" function. In RoStrap's case, it eliminates the need for absolute paths between your code and handles replication of shared code in the background.

In a perfect world, it would be nice for `import { something } from "Aurora"` to compile to `Resources:LoadLibrary("Aurora")`, where "Aurora.ts" is the name of one of your own files.

Even if a compromise is required, it would be nice to support emitting import statements that are compatible with frameworks while not losing type information about the module.

In RoStrap's case, relative file-based import statements should still use `require`, only the named module syntax should use `Resources:LoadLibrary`.

**Comment by osyrisrblx** [comment]
This will need additional investigation into exactly how imports should work.

**Comment by Dog2puppy** [comment]
Will there be support for [AeroGameFramework](https://github.com/Sleitnick/AeroGameFramework)?

**Comment by evaera** [comment]
@Dog2puppy Could you give an example of what the special import statement would need to look like to be compatible with that? We'd want to implement this as generically as possible so that we can cover as many use cases as we can.

**Comment by Dog2puppy** [comment]
In AeroGameFramework there's multiple modules you make for clients and the server. On the server theres services and modules, and the client has controllers and modules. The services and the controllers are all executed when the framework starts and what your services and controllers return has a few dictionaries injected, services, controllers (for clients only), and modules. So then you can do something like this. 
```lua
local MyService = {}
local OtherService

function MyService:Start()
     OtherService:Add(1, 1) -- 2
end

function MyService:Init()
     OtherService = self.Services.OtherService
end```

Not sure how this would be like in TypeScript though. Maybe something like this? 

```typescript
import { OtherService } from services
```
There might be some other way that works better. I don't really understand how it would work.

**Comment by evaera** [comment]
The best way to do this might be to just make an external module, named `services`, that dynamically returns AeroGameFramework services based on the name you try to import. This might be possible for the RoStrap use case as well...

**Comment by Dog2puppy** [comment]
Wouldn't npm make RoStrap redundant?

**Comment by evaera** [comment]
The package manager part, yes, but RoStrap also has a [module loader](https://rostrap.github.io/Resources/) called Resources which is somewhat similar to the services in Aero. Resources can also do some cool stuff with instance generation, simplifying the client/server model.

**Comment by Dog2puppy** [comment]
> The best way to do this might be to just make an external module, named services, that dynamically returns AeroGameFramework services based on the name you try to import.

@evaera How would I import a service using this method like `import { X } from "services'` instead of `import { X } from "./../../../services`?

**Comment by osyrisrblx** [comment]
@Dog2puppy This would be done by creating an npm module. I'll post a guide for how to make these soon.

**Comment by Dog2puppy** [comment]
Why was this closed?

**Comment by evaera** [comment]
We decided that support for third party frameworks should live in modules, not the compiler.

**Comment by Dog2puppy** [comment]
Okay. Any ETA on the RoStrap module?

**Comment by evaera** [comment]
Not sure yet. I'll be getting to it when I get some free time here soonish. Probably will be a few weeks yet.
