### ISSUE TITLE
Relative path compiles incorrectly

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#30]
As a quick example, I have a TypeScript file with a block of import statements which look like this:
```TypeScript
import { Base, RoadPoint, OwnerChangeContext, BaseOwnerChangedEvent, RoadPointOwnerChangedEvent } from '../../Config/Maps'
import { State, StateFactions, Factions, Assets } from '../../Config/States'
import { Config } from '../../Config'
import { HttpService, DataStoreService } from 'rbx-services'
import { OwnershipJson, OwnershipDeserializer } from './OwnershipJson'
```

The compiled Lua:
```Lua
-- luacheck: ignore
local TS = require(game.ReplicatedStorage.RobloxTS.Include.RuntimeLib);
local _0 = require(script.Parent.Parent.Parent.Config.Maps);
local Base, RoadPoint, OwnerChangeContext, BaseOwnerChangedEvent, RoadPointOwnerChangedEvent = _0.Base, _0.RoadPoint, _0.OwnerChangeContext, _0.BaseOwnerChangedEvent, _0.RoadPointOwnerChangedEvent;
local _1 = require(script.Parent.Parent.Parent.Config.States);
local State, StateFactions, Factions, Assets = _1.State, _1.StateFactions, _1.Factions, _1.Assets;
local Config = require(script.Parent.Parent.Parent.Config).Config;
local _2 = require(TS.getModule("rbx-services", script.Parent).out.index);
local HttpService, DataStoreService = _2.HttpService, _2.DataStoreService;
local _3 = require(script.Parent.OwnershipJson);
local OwnershipJson, OwnershipDeserializer = _3.OwnershipJson, _3.OwnershipDeserializer;
```

The issue is that any relative paths, in this case `../../Config` and the likes, are compiled with an extra `Parent` in Lua. So, `import { Config } from '../../Config'` is becoming `require(script.Parent.Parent.Parent.Config).Config`

**Comment by osyrisrblx** [comment]
Hmm is this an index file? I think that might be the problem.

**Comment by TripleFrequency** [comment]
Yes, `../../Config` is actually `../../Config/index`. But the issue still exists for the `States` and `Maps` files. Here is a screenshot of my project structure: 
![image](https://user-images.githubusercontent.com/6166013/46571738-5f63bb80-c948-11e8-97d4-377f7fca88f6.png)

**Comment by TripleFrequency** [comment]
You can also see in my example that my import from `rbx-services` is being compiled incorrectly. It appends a `.index` on the end, which is clearly invalid.

**Comment by osyrisrblx** [comment]
That issue is now fixed for rbx-services, please use `npm update` to get the latest version.

**Comment by osyrisrblx** [comment]
Also, what file is your code example from?

**Comment by TripleFrequency** [comment]
The imports are from OwnershipHandler.server.ts
