### ISSUE TITLE
for...in loops give wrong type to key variable

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#301]
Consider the following:
```ts
const Players: Players = game.GetService("Players");
const players: Array<Player> = Players.GetPlayers();

for (const i in players) {
	// `i` is a string in TS, but a number in Lua
	// For whatever reason, you can index `players` with string i:
	const plr: Player = players[i]!;
	const x: string = i + 1; // 01, 11, 21, 31, 41, 51, etc

	// but here, you cannot index `players` with an arbitrary string:
	const plr2: any = players[i + 1];
}
```
`i` is the wrong type for us, but we can *pretty much* get away with just letting it be the wrong type, because it will not let us index the `players` with any string besides `i`. Also, due to Lua's implicit casting, things like `i + 1` will properly transpile to a string (`i .. 1`). However, if someone passes `i` into a function, TS will think it is a string and that wouldn't be good.

The best solution would be to somehow define `i` to be a number instead of a string (in es.d.ts), but I do not know how we would do that. I believe the problem stems from this unfortunate JS reality:

```js
var x = [10];
console.log(x[0]); // 10
console.log(x["0"]); // 10
```

As for the alternative solutions, we could do:
```lua
local Players = game:GetService("Players");
local players = Players:GetPlayers();
for _0 = 0, #players - 1 do
	local i = tostring(_0);
	-- we would have to make an exception for players[i]
	local plr = players[_0 + 1];
	-- OR we would need to make arrays indexable by strings:
	local plr = players[tonumber(i) + 1];
end;
```
If we cannot solve this problem in `es.d.ts`, the cleanest solution from the transpiler's perspective would be to make arrays indexable by strings by wrapping strings in `tonumber(...) + 1`. Even though that could be a decent solution, this would make for...in loops far less performant than one would expect. For this reason, I would recommend disabling for...in loops for arrays.

Currently this gives the wrong Lua output as well:
```ts
for (const i in players) {
	const plr: Player = players[i]!;
}
```
```lua
for i = 0, #players - 1 do
	local plr = players[i]; -- should be i + 1
end;
```

If someone needs to iterate over an array with an index and value, the most performant way is as follows:
```ts
const lastIndex = players.length - 1;
for (let i = 0; i <= lastIndex; i++) {
	print(i, players[i]);
}
```
Transpiles to:
```lua
local lastIndex = (#players) - 1;
for i = 0, lastIndex do
	print(i, players[i + 1]);
end;
```

**Comment by evaera** [comment]
The reason for this is because arrays are just objects in JS whose keys are still strings which just happen to take the shape of integers ascending from `0`. Every time you index into an array in JS, the number is casted to a string since objets can only have string keys.
