### ISSUE TITLE
namespaces and functions can overlap in TS

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#302]
This is valid TS:
```ts
function foo() {}
namespace foo {
	export const bar = 1;
}

foo();
```
Outputted Lua:
```lua
local foo;
local foo = function()
end;
foo = foo or {} do
	local _0 = foo;
	local bar = 1;
	_0.bar = bar;
end;
foo();
```
Recommended fix: disallow namespace/function name collisions. The ideal solution would be to force people to set a `tsconfig.json` value which disallows this case.

**Comment by osyrisrblx** [comment]
Which tsconfig option would disallow this?

**Comment by evaera** [comment]
Important: The fix for this should only apply to namespaces used as values. Namespaces which contain types merging with functions is probably still fine and I believe was an intentional allowance when originally implementing this

**Comment by Validark** [comment]
Alternatively, we could support this with a __call metamethod
