### ISSUE TITLE
Roblox-TS should get a `Number` namespace

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#309]
I am particularly a fan of the [constant values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Properties) which are nice to have. It would be particularly useful to also have some kind of value for the maximum 32 bit integer, because Roblox uses 32 bit integers for a significant number of properties. For example, if you want to create a ScreenGui with the highest possible `DisplayOrder`, you can set it to `Number.MAX_INTEGER_32` (which is 2^31 - 1). I would prefer that these constants compile to in-line values.

**Comment by evaera** [comment]
I think this is probably against our project pillars and non-goals. I think that this sort of thing would fit better into a package instead of creating a new namespace to match JS.

**Comment by osyrisrblx** [comment]
I agree with @evaera , this would probably be best as a package.
