### ISSUE TITLE
Readonly class properties assigned in-line should go in __index

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#310]
On the Lua side, we can put readonly properties in the __index metatable to save memory because we know they will never change. Of course, this is only true of built-in immutable objects (strings, numbers, booleans) and Readonly objects, although the latter have far less of a use case in my view and I would be content with logic applying solely to the former. 

One should also note that expressions involving function calls are valid in-line property assignments, so this should only apply to readonly string literals, numeric literals, and boolean literals. This would make a massive difference though, since most objects have some kind of information about what kind of object it is. Case in point: `ClassName`

**Comment by Validark** [comment]
It would also be nice to allow one to easily create an alias function. For example if a function `do()` is defined in a class, `public readonly go = this.do;` should transpile to `__index.go = __index.do`

**Comment by osyrisrblx** [comment]
Wouldn't this be broken by `readonly x = new X() ;`?
