### ISSUE TITLE
Static function for class should not take self parameter

### ISSUE THREAD

**Issue by ckdavid** [roblox-ts/roblox-ts#319]
I tried compiling a class that included:
```
export class Path {
	static parse(pathString: string) {
		// body
	}
}
```
but the generated code was of the form
```
Path = {
		parse = function(self, pathString)
			-- body
		end
	}
```
which includes a `self` parameter that I don't think should be there. This means that when calling `Path.parse("somestring")`, the argument would be discarded, as it was bound to `self`.

**Comment by Validark** [comment]
The outputted code is correct. When you call `Path.parse`, it transpiles to a method call, e.g. `Path:parse("");`. This is necessary because you can access members from `this` in a static method.
