### ISSUE TITLE
Import aliases not compiled

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#32]
When you use `import X as Y`, it is not compiled with the alias:
```TypeScript
import { X as Y } from './Test'
print(Y)
```
Becomes
```Lua
local X = require(script.Test).X;
print(Y);
```
I also assume it is known that syntax like this doesn't export anything in the compiled Lua:
```TypeScript
const X = false
export { X }
```
Using `export { X as Y }` also does nothing. If you want to investigate this further, I can make a separate issue for it as well.

**Comment by osyrisrblx** [comment]
Fixed this, I'll make another issue for the export thing. 👍
