### ISSUE TITLE
Add support for parameter properties

### ISSUE THREAD

**Issue by ckdavid** [roblox-ts/roblox-ts#320]
I tried defining a constructor using
```
export class Path {
    constructor(readonly components: string[]) {
    }
}
```
and the generated code didn't assign the parameter to the constructed instance. The output for the constructor was
```
Path.constructor = function(self, components)
    return self;
end
```
whereas I would have expected an assignment of `self.components = components` before the `return`.

**Comment by Validark** [comment]
If you put `public`, `private`, or `protected` before `readonly`, your code will work. I believe this is a problem in ts-morph. `components` apparently isn't getting placed into the `public` array, as it should be, even though it is implicitly `public` by having a `readonly` modifier.
