### ISSUE TITLE
TS.add should be removed in favor of erroring

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#328]
This seems like a footgun to me. We don't want unexpected behavior occurring at run-time.

**Comment by Validark** [comment]
Newer versions of TypeScript also support a `string.concat` method. We could easily add this method and macro it to the `..` operator.

**Comment by osyrisrblx** [comment]
Could you provide an example of what the unexpected behavior would be? I thought TS.add() pretty well emulates the `+` operator for places where we can't be sure of types.

**Comment by Validark** [comment]
`TS.add()` does pretty well emulate the `JS` operator. My point was that this is a potential footgun for the developer. It would be better if we only allowed the `+` operator on same-typed operands, and informed people to call `tonumber` or use `string.concat` instead to get the behavior they want.

**Comment by osyrisrblx** [comment]
Going to close this for now. Maybe we can add a warning in the future for cases like this.
