### ISSUE TITLE
Add opcall

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#332]
Not sure what to call this, but for now I'll refer to it as `opcall()`

Right now, pcall is really hard to use well. To demonstrate this, let's describe a simple function that might error:
```TS
function foo(x: number) {
	if (x > 0) {
		return math.sqrt(x);
	} else {
		throw "x must be more than 0!";
	}
}
```

If we use pcall normally, it would look like this:
```TS
const [success, valueOrError] = pcall(foo, 1);
if (success) {
	valueOrError; // string | number
} else {
	valueOrError; // string | number
}
```
This isn't good because `valueOrError` doesn't have good types.

You could also try not destructuring the pcall return immediately:
```TS
const result = pcall(foo, 1);
if (result[0]) {
	const value = result[1]; // number
} else {
	const errorMsg = result[1]; // string
}
```
That's better, but it's not very ergonomic to use `if (result[0]) {`. It's also not really clear when reading the code what you're doing there.

I propose a new version of pcall that would have the following signature:
```TS
declare function opcall<T, U extends Array<any>>(
	cb: (...args: U) => T,
	...args: U
): { success: true; value: T } | { success: false; error: string };
```
And it's usage would look like:
```TS
const result = opcall(foo, 1);
if (result.success) {
	result.value; // number
} else {
	result.error; // string
}
```

**Comment by Dog2puppy** [comment]
What’s the advantage of this compared to try catch?

**Comment by Validark** [comment]
I like the way it looks to check against `result.success` and `result.value`. 👍

**Comment by osyrisrblx** [comment]
@Dog2puppy try/catch doesn't actually give you a type for the `e` argument in the catch clause.

**Comment by osyrisrblx** [comment]
I'm also open to naming alternatives.

**Comment by Validark** [comment]
opcall - object pcall
epcall - explicit pcall
vpcall - verbose pcall
dpcall - dictionary pcall
tpcall - table pcall or toilet paper call

**Comment by osyrisrblx** [comment]
inspired by PHP:
real_pcall
