### ISSUE TITLE
Statically-initialized data structures not compiled

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#35]
I can confirm this issue occurs with maps and sets, and likely anything else that allows static initialization in its constructor:
```TypeScript
let testSet = new Set(["Test", "OtherTest", "MoreTest"])
let testMap = new Map([["TestKey", "TestVal"], ["OtherTestKey", "OtherTestVal"]])
```
Compiles to:
```Lua
local testSet = {};
local testMap = {};
```

**Comment by osyrisrblx** [comment]
Decided originally to not support these. Looks like they accidentally made it into the type definitions. I suppose I could statically initialize it into what the Lua should look like.

**Comment by ckdavid** [comment]
I tried compiling a class that included:
```
export class Path {
	static parse(pathString: string) {
		// body
	}
}
```
but the generated code was of the form
```
Path = {
		parse = function(self, pathString)
			-- body
		end
	}
```
which includes a `self` parameter that I don't think should be there. This means that when calling `Path.parse("somestring")`, the argument would be discarded, as it was bound to `self`.
