### ISSUE TITLE
FunctionExpressions in ObjectLiteral PropertyAssignments should be considered methods

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#351]
FunctionExpressions in ObjectLiteral PropertyAssignments should be considered methods to fix this problem:

TS:
```ts
const O = {
	// tslint:disable
	// prettier-ignore
	a: function () {
		print(this.a);
	}
};

O.a();
```
Compiled:
```lua
local O = {
	a = function() -- should have self
		print(self.a);
	end;
};
O.a(); -- should be a method
```

From my testing, this was the only case I found where a problem such as this can occur. It seems our class implementation doesn't have any issues handling these cases.

**Comment by osyrisrblx** [comment]
Odd, I would think `this` inside the function would refer to the function itself. But it refers to `O` instead?

**Comment by Validark** [comment]
It does indeed.
