### ISSUE TITLE
Support new Color3.fromRGB() syntax

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#391]
I would prefer to switch all of our built-in constructors over to using the new keyword. This is pretty easy to do, especially since we already have the infrastructure to do this.

For example:
```ts
new Color3()
new Color3.fromRGB()
new Color3.fromHSV()

new CFrame()
new CFrame.fromAxisAngle();
new CFrame.fromEulerAnglesXYZ();
new CFrame.fromEulerAnglesYXZ();
```

**Comment by osyrisrblx** [comment]
Sorry, but I disagree from a design perspective.
In a general form, `new X()` should compile to `X.new()`.

Also with other TS libraries like ThreeJS, static constructors are just functions. This seems like something we should follow.
