### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by 11reed** [roblox-ts/roblox-ts#413]
Getting these errors when I run ``rbxtsc -w``

![image](https://user-images.githubusercontent.com/29209706/58724257-1c0ffe80-83aa-11e9-8250-d9fb23763c49.png)

![image](https://user-images.githubusercontent.com/29209706/58724286-31852880-83aa-11e9-82bb-d63d57f96d15.png)

So I'm not really sure exactly what this is.
Also, when set ``"isolatedModules": false``to false I still cannot compile my ts.
My tsconfig file is just from the example on the website.

rojo.json

![image](https://user-images.githubusercontent.com/29209706/58724361-5e394000-83aa-11e9-83db-738c11f3a6f5.png)

directory structure

![image](https://user-images.githubusercontent.com/29209706/58725487-4ca56780-83ad-11e9-9145-90ec378f3a47.png)

**Comment by osyrisrblx** [comment]
Try renaming `rojo.json` to `default.project.json` (the new Rojo format)

We're still in the process of updating our docs to include that.

Also you are required to have at least one `export` statement in each file. If you do not want to export anything, simply put `export {};` at the top or bottom of the file.

Let me know if you need anymore help!

**Comment by osyrisrblx** [comment]
I realized your rojo.json is also using the old format, here's what the new format looks like for your project:
```JSON
{
	"name": "motorbike",
	"tree": {
		"$className": "DataModel",
		"ServerScriptService": {
			"$path": "ServerScriptService",
			"My Project": {
				"$path": "Game"
			}
		},
		"ReplicatedStorage": {
			"$className": "ReplicatedStorage",
			"roblox_ts_include": {
				"$path": "include"
			}
		}
	}
}
```

**Comment by 11reed** [comment]
I got it working, but default.project.json does not work. I changed to the new format though which did work. It also only compiles in vscode but, not to roblox studio.

**Comment by osyrisrblx** [comment]
Ah sounds like you're using the old version of Rojo. I recommend updating to Rojo 0.5.0-alpha.11.

**Comment by 11reed** [comment]
It's working completely fine now, thank you for the help.
