### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by scriptis** [roblox-ts/roblox-ts#422]
At the time of writing, `rbxtsc` requires that a `package-lock.json` file be present in the project root in order to run, so that it can validate the version of `@rbxts/types`: [see here](https://github.com/roblox-ts/roblox-ts/blob/2da3438cb5f0a554c051bbb1c527b3612d70d253/src/Project.ts#L298-L335).

[Yarn](https://yarnpkg.com/en/) is an alternative to npm that supports local caching and user-level global binaries, preferred by many. While it has nearly identical functionality to npm, and uses the npm registry by default, it does not create a `package-lock.json`. Yarn instead creates a `yarn.lock`, with an entirely different structure.

Is there any reason not to just use `package.json` instead of `package-lock.json` for this check instead?

**Comment by osyrisrblx** [comment]
package.json uses semver ranges which doesn't give us a clear view of what's actually installed. package-lock.json does give us the exact semver. I'd be willing to investigate if we could support yarn. :+1:

**Comment by evaera** [comment]
Perhaps we could use `npm list @rbxts/types` or check the package.json inside the package directly?

-----------------

And JSYK, npm also supports local caching and most every feature that set Yarn apart at its inception. For me, yarn just doesn't offer enough advantage over npm to warrant the trouble. As a compiler I still think we should be unopinionated, but personally I don't think there's much value to gain from using yarn.
