### ISSUE TITLE
Compiled require calls should use Instance.WaitForChild

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#43]
Currently, all absolute paths are compiled to assume all replication and loading is already completed. There are no `WaitForChild` calls, and so I find my scripts failing to load properly.

For example, this is one of my imports:
```Lua
local TeleportUtil = require(game.ServerScriptService.TeleportUtil.MainModule)._default;
```
It consistently errors when I start the game (on a server). I am suggesting it be compiled to something like:
```Lua
local TeleportUtil = require(game:GetService("ServerScriptService"):WaitForChild("TeleportUtil"):WaitForChild("MainModule"))._default;
```

**Comment by osyrisrblx** [comment]
So I'm a little bit confused on why this is happening.

From the server, nothing is run until after deserialization is complete. The only place this might be an issue is somewhere like ReplicatedFirst on the client, but you're requiring from ServerScriptService which doesn't ever replicate to begin with?

**Comment by TripleFrequency** [comment]
In my particular instance, I use evaera's `Game Module` plugin. Basically, all of the game's scripts/contents are loaded in each server when it starts up by a call to `require`. Could this cause loading issues like I am seeing?
