### ISSUE TITLE
Roblox-TS is a transpiler.

### ISSUE THREAD

**Issue by Masken8** [roblox-ts/roblox-ts#435]
![image](https://user-images.githubusercontent.com/26001144/58861113-f20e5300-86ad-11e9-8fc8-dbaf5283ce21.png)
https://en.wikipedia.org/wiki/Source-to-source_compiler

**Comment by osyrisrblx** [comment]
You're not wrong! However..

A "Transpiler" is a not-so-formal term for a type of compiler. Given that it's not a word you can find in most dictionaries, and "compiler" is still correct: I decided not to use it.
