### ISSUE TITLE
Broken comments

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#464]
It breaks if the following comes after all other code in the file:

```ts
/**/
// bad!
```

Also, `/**/` put somewhere in between code will not be compiled.

**Comment by osyrisrblx** [comment]
I'm not sure we could ever support comments randomly between expressions. I think they're pretty rare anyways.

**Comment by Validark** [comment]
Also, we currently support this:
```ts
/* a */
function f(s: string) {
	print(s);
}
```
But not this:
```ts
/** a */
function f(s: string) {
	print(s);
}
```
I am guessing this is because making a JSDoc comment attaches it to the function node instead. It would be nice to support comments on functions.

**Comment by Validark** [comment]
We should also try to indent the `--` itself, when applicable
```ts
{
	{
		{
			// go awae!
			print("hey");
		}
	}
}
```
```lua
do
	do
		do
-- go awae!
			print("hey");
		end;
	end;
end;
```
