### ISSUE TITLE
Ban footgun of destructuring a method from an object

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#465]
```ts
function f(o: Instance) {
	const { FindFirstChild } = o;
	FindFirstChild("Hello"); // in TS, we have no opportunity to pass in `this` manually!
	const g = o.FindFirstChild;
	g("World!");
}
```

**Comment by Validark** [comment]
New `this` contexts in our types solves this problem.

**Comment by osyrisrblx** [comment]
[I still think this needs to be solved for stuff like this](https://roblox-ts.github.io/playground/#code/MYGwhgzhAEAa0G8BQ1XQgFzBglsaARmAE7QC80AREcZQNwpqbZ7QBmA9hwBQCUijNGgAOxHADsM3DAAscEAHQ1eDIQF8kGpMOBgQIbrAWcOKoA)

**Comment by Validark** [comment]
Things like that example should definitely be considered alongside https://github.com/roblox-ts/roblox-ts/issues/718
