### ISSUE TITLE
Support declaration files and/or modules

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#5]
- Support importing directly from a *.d.ts file
- Consider module-based declarations starting with `game.` or `script.`

**Comment by osyrisrblx** [comment]
Decided to not support the `script.` prefix for now, allowing only `game.`.

The reason for this is that every .ts file in your project has a different relation to the given module. Instead, you should use the first method and put a `.d.ts` inside your `src` folder
