### ISSUE TITLE
Make truthy/falsy values match the TypeScript type system

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#503]
# Update
This issue will be closed by https://github.com/roblox-ts/roblox-ts/pull/511. Please note that the examples given here are actually incorrect. After further thinking and testing, I discovered the translated code below is not equivalent. The problem basically comes down to the fact that `a && b` will evaluate to `a` when `a` is falsy. If `a` is `""`, for example, then `a && b` will evaluate to `""`.

Thus, the optimal solution involves if statements.
```ts
function f(a: string, b: string) {
    const x = a && b;
}
```
```lua
local function f(a, b)
	local x = a;
	if x ~= "" then -- a && b
		x = b;
	end;
end;
```

# (Outdated) Design Outline
## Problem
The TypeScript type system can't understand cases like these unless we match TS truthy/falsy values:

```ts
function foo(n?: number) {
    const x = n ? n : n;
}
```

## Solution
Make roblox-ts generate type-based code which checks whether a value is truthy/falsy. The only ways in which Lua's truthy/falsy evaluation differs is with `""`, `0` and `NaN`. To check whether a number is NaN, check if `a == a` is false since NaN values are not equal to anything, even itself.

## Examples
1.
	```ts
	function f(a: string, b: string, c: string) {
	    const x = (a && b) || c;
	}
	```
	```lua
	-- notes: `and/or id` should always be last
	-- the last or condition doesn't need any additional checks
	local function f(a, b, c)
	    local _0 = a ~= "" and b
	    local x = _0 ~= "" and _0 or c;
	end;
	```
2.
	```ts
	function f(a?: string, b?: string, c?: string) {
	    const x = (a && b) || c;
	}
	```
	```lua
	-- Making a, b, c all optional only adds on additional check to this case:
	local function f(a, b, c)
	    local _0 = a ~= "" and a and b
	    local x = (_0 ~= "" and _0) or c;
	end;
	```
3.
	```ts
	function f(a?: string, b?: string, c?: string, d?: string) {
	    // these two lines should be equivalent
	    const x = a || b || c || d;
	    const y = (a !== "" && a) || (b !== "" && b) || (c !== "" && c) || d;
	}
	```

## Implementation details
- Inside a truthy check, e.g. `if (a)`, expand `a` to `a ~= 0 and a == a and a ~= "" and a` if `a` is assignable to a `number`, `string` and `undefined` (we don't support `null` values).
    - Checks can be eliminated accordingly if a type is guaranteed to be none of these.

### Definition of a truthy check
- Truthy checks can occur in the following expression/statement types:
    1. if statements `if (a)`
    2. while statements `while (a)`
    3. do..while statements `do {} while(a)`
    4. ternary conditional expressions `a ? 1 : 0`
    5. unary/binary expressions `a && ""`
        - Anything on the left-hand side of an `&&` or `||` operator is checked for truthy-ness
        - Anything inside a NotExpression is checked for truthy-ness

### Other notes
- This implementation should call `assertNonTuple` to expand protections against https://github.com/roblox-ts/roblox-ts/issues/349

**Comment by osyrisrblx** [comment]
We should try and add tests for each case mentioned here.
