### ISSUE TITLE
Question/feature suggestion

### ISSUE THREAD

**Issue by CleverSource** [roblox-ts/roblox-ts#505]
I don't expect you have any plans for this or would plan to maintain something like this but a lua to TypeScript would be interesting, not to replace this but to add-on with it possibly?

Edit: Roblox Lua to Typescript

**Comment by osyrisrblx** [comment]
This isn't really feasible because you're going from less info -> more info (types). Even with some smart type inference stuff, you still have to define unknown types.

**Comment by Validark** [comment]
You can already use Lua with roblox-ts by creating a .d.ts file with type definitions
