### ISSUE TITLE
varargs which end in an undefined lose their size with no TS solution

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#514]
## Use cases
- inspect function
- console.log implementation

## Problems
- **The aforementioned cases currently cannot be written in TS**.
- Developers should be protected from hitting this footgun. 

## Goals
- Write a solution which outputs relatively simple and optimized code. For example, a bad solution would be making varArgs a `newproxy(true)` with a `__len` metamethod, which also masks and acts like an array due to `__index` and `__newindex` metamethods. This would also break things when someone tries to call `typeIs` or `typeOf` and it returns `userdata` instead of `table`.

- Keep the codebase somewhat neat, so we will have useful helper functions we can just plug-in throughout the codebase.

## Proposed Solution

Preserve function variadic arguments!

- Reimplement the optimization I introduced in https://github.com/roblox-ts/roblox-ts/pull/200 which was removed in https://github.com/roblox-ts/roblox-ts/pull/222. The reason it couldn't be fixed before is because our old system outputted IIFE's for TS-only operators (`++`, `a?b:c`, `--`) which meant we couldn't tell at compile-time whether a given function had a closure in it. Now, we have a much more intelligent system which drops the expressions in-line.
    - Only if there are closures in the function that use the varArgs, make a table `_0 = {...}`
    - Alias all `.size()` calls to a variable initialized at the top of the function to `_1 = select("#", ...)`
    - Alias all `.isEmpty()` calls to `_1 === 0` (see above)
    - Alias all spread to `...` or `unpack(_0, 1, _1)`
    - Alias destructuring or accessing to `select(i + 1, ...)` or `_0[i + 1]`

- Force all varArg declarations which can contain a trailing `undefined` to be a `ReadonlyArray`. For example, if we call a varArg with a stack `(undefined)`, we can properly read `select(1, ...)` or `args[1]`, but we cannot push to it dynamically after the size variable (`_1` above) changes.
    - Disallow all `ReadonlyArray` functions we can't intelligently compile in-line. (for loops need to use the logic described above)
    - This would primarily affect varArgs of type `Array<unknown>`.
    - Disallow passing varArg arrays as an argument in function calls. We would suggest that the developer use `.copy()`

### Note
- varArgs of type `Array<string | number | boolean>` would not have any restrictions placed on them. Only if the array can have undefined members do we need to impose restrictions.

**Comment by osyrisrblx** [comment]
Until we find a solution, we should throw a CompilerError if the type of a var args is nullable.

**Comment by osyrisrblx** [comment]
Closing this in favor of #1070 .
