### ISSUE TITLE
Unlock typeRoots field in tsconfig.json

### ISSUE THREAD

**Issue by ddavness** [roblox-ts/roblox-ts#515]
Currently, roblox-ts will refuse to boot up if the `typeRoots` field from `tsconfig.json` is not exactly `["node_modules/@rbxts"]` and then will proceed to throw an error. This is a very inflexible approach that may cause issues for larger projects.

While this is ok for most projects, there are cases where allowing to change this setting makes sense.

**Main Use Case:** Multi-place projects. Those have a root folder (with stuff that is common to all of them) and then each place has it's own folder. Since we cannot have a `tsconfig.json` file that serves all the places, we would need to have the `node_modules/@rbxts` directory in every place directory separately.

Current workarounds for this issue are:
- Installing a separate copy of `rbxtypes` for each place - this is terribly inefficient because you need to update all of them individually (unless npm has something to update them all at once), and because it adds a lot of overhead on repositories;
- Creating symlinks to the root `node_modules` folder in order to fool the program into thinking that it's accessing the directory - also far from ideal as administrative and permission related issues can arise (Creating a local, relative-path symlink requires tweaking the Local Security Policy on Windows to grant the user the required permissions to do so).

**Solution Proposal:**
1. Drop the `typeRoots` checks (almost) entirely - the most prone to anti-patterns such as renaming everything to weird names;
2. Keep the checks but do not throw errors - log warnings instead if the user starts to use anti-patterns (e.g. renaming the target directory to `weirdname/unrecognizable`) - unless the directory doesn't actually exist.
3. Adjust the rule so that the string **ends** in `node_modules/@rbxts` instead of **being exactly** `node_modules/@rbxts`, so that strings like `../node_modules/@rbxts` are recognized.

**Comment by osyrisrblx** [comment]
Need to also investigate how nodejs resolves modules outside of the "project directory".
