### ISSUE TITLE
Exit Confirmation cannot recognize between Y and N

### ISSUE THREAD

**Issue by ddavness** [roblox-ts/roblox-ts#523]
## Description

The current way to stop a `roblox-ts` job is to send an interrupt signal (`SIGINT` for Linux/macOS, and equivalent on Windows). This is usually done via `Ctrl + C`.

The current behaviour asks for confirmation before exiting;

`Terminate batch job (Y/N)?`

However, the program completely disregards whether the user input is `Y` or `N` and exits anyways.

Below, a simple reproduction:
![image](https://user-images.githubusercontent.com/45321798/60852670-98d79900-a1f0-11e9-9c17-63c7dedc05e5.png)

## Expected Behavior
Processes shouldn't terminate when `N` or `n` is given as input.

**Comment by osyrisrblx** [comment]
Hmm I think this might be a NodeJS or Chokidar thing. I'll see if I can provide a workaround.

**Comment by TheWaffleDimension** [comment]
This is controlled by the command interpreter on Windows (Windows Console). It results when the application is started from a batch job and isn't asking if you want to stop the process itself, only the process (the batch file) that started it. The only way to prevent this would be to rewrite and recompile Windows Console, and then redistribute that, which wouldn't be within the scope of roblox-ts.

**Comment by ddavness** [comment]
Can confirm this behaviour of .bat/.cmd files

![image](https://user-images.githubusercontent.com/45321798/60901622-2dc8a980-a266-11e9-9441-f1758d324e67.png)

This suggests to me that the main process (chokidar, maybe) has it's own signal handler and disregards whether the process that launched it is still active or not.
So basically when the command is executed, the launcher process is subject to confirmation whereas roblox-ts has exited already.

This is likely also coherent with the behavior seen on GNU/Linux based systems where the watch process exits without confirmation once a `SIGINT` signal is sent.

**Comment by osyrisrblx** [comment]
https://github.com/paulmillr/chokidar/issues/528
