### ISSUE TITLE
Support delete statement

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#547]
Currently, we support this (kinda):

```ts
const f = {
	x: 1,
};

f.x = undefined!;
```

However, in JS, `f.x` is still a real field. Run this in the browser
```js
const f = {
	x: 1,
};

f.x = undefined;
console.log(Object.keys(f)); // ["x"]
```

In Lua, setting a field to `nil` means it is no longer a field. I.e. there is no longer a slot called "x" when setting `f.x` to `nil`. In JS, setting a field to `undefined` does not delete the field. `delete` statements do.

Hence, `delete` is the proper choice, and setting a value to `undefined` is technically incorrect.

We could ban doing `f.x = undefined` to avoid confusion, and, when assigning a value to a nullable union, force the developer to delete if undefined, else assign.

```ts
const o = { a: 1 };
declare function f(): number | undefined;

o.a = f()!; // this would become invalid

const newA = f(); // this would become preferred
if (newA) o.a = newA;
else delete o.a;

// or this
newA ? o.a = newA : delete o.a;
```

Otherwise, we could just document this behavioral difference and allow either.

**Comment by osyrisrblx** [comment]
It seems like the `delete` operator isn't actually type safe?

```TS
const foo = {
	x: 1,
};

delete foo.x; // allowed
foo.x = undefined; // not allowed (error)

foo.x; // number
```

If anything, I would prefer to just ban the `delete` operator.

**Comment by Validark** [comment]
I agree. Until such a time as the `delete` operator is actually type-safe, it is probably not a good idea to support it. I don't think we should change the name of Object.keys, but we should document it on the website that setting a value in an object to undefined is equivalent to deleting in JS.
