### ISSUE TITLE
Compiler should help user set up the required files for new projects

### ISSUE THREAD

**Issue by ddavness** [roblox-ts/roblox-ts#558]
# This is a draft.

Currently, we need to copy and paste template files from the [Quick Start](https://roblox-ts.github.io/docs/quick-start) documentation.

**This approach does work, but I'm lazy and I want a faster way!**

## Suggestion:

If the files do not exist, whip out the ones within the documentation and put there in the workspace.

**OR**

Add a new command to the compiler (**Example:** `rbxtsc init`) to guide the user with this process.

**Comment by osyrisrblx** [comment]
possible duplicate of #278

**Comment by ddavness** [comment]
Confirmed duplicate. Closing.

**Comment by osyrisrblx** [comment]
Feel free to add any ideas you have on this topic to that issue as a reply. :+1:
