### ISSUE TITLE
Rework LuaTuple destructuring optimizations

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#577]
I need to go back and redo all of the code for our LuaTuple destructuring optimizations. It's a bit old and uses bad APIs. Need to move code into binding.ts and then maybe make things a bit more generic.

Also should fix #354 while I'm at it.

**Comment by Validark** [comment]
#354 was fixed when you changed the destructuring system to pass around the type. https://github.com/roblox-ts/roblox-ts/issues/563 may have been a duplicate.
