### ISSUE TITLE
Inform users of package update

### ISSUE THREAD

**Issue by ddavness** [roblox-ts/roblox-ts#584]
It might be likely that users will not update the compiler if they're not actively tracking the repository or in discord.

My suggestion is then that the compiler, when ran, will compare itself against the npm registry. If theres a new version, then notify the user.

### Some quirks I suggest in order to be as lightweight and as little annoying as possible:

- Only check for updates every X hours, instead of every time we run `rbxtsc`;
- Only notify the user once per release. **Example:** We are currently in version 0.2.14. Once version 0.2.15 gets out, user is notified. Then, they only get another notification once version 0.2.16 is out.
- Possibly add a way to opt-out similarly to the `--noAnalytics` flag.

**Comment by Validark** [comment]
Also, roblox-ts should still work even if your internet is off.

**Comment by ddavness** [comment]
Yes, if for some reason the registry cannot be accessed (no internet connection, website blocked (unlikely but can happen), etc.), operation should continue as normal.

Whether to silently fail and skip this process or tell the user that "we couldn't search for updates", I guess it might be up to the community/developers to decide so.

**Comment by Validark** [comment]
In my opinion, it should check silently every 12 or 24 hours for a new release.
