### ISSUE TITLE
Flag in rbxtsc to hide the compiler comments at the top

### ISSUE THREAD

**Issue by Vorlias** [roblox-ts/roblox-ts#613]
[rbx-net](https://github.com/roblox-aurora/rbx-net) is now available for Lua use (to replace the old ModRemote), and as a consequence of that, each time the Lua library code is compiled it the header comments will count as commits.

An ability to disable the compiler comments at the top of files would be much appreciated. :)

**Comment by Validark** [comment]
Fixed by #625

**Comment by osyrisrblx** [comment]
Actually, I scrapped #625, it didn't get merged.

**Comment by Vorlias** [comment]
> Actually, I scrapped #625, it didn't get merged.

Haha, thought so. :eyes:
