### ISSUE TITLE
Compiler errors are not verbose enough

### ISSUE THREAD

**Issue by unix-system** [roblox-ts/roblox-ts#637]
I think we should modify some of the compiler outputs for known behavior that causes compiler errors.

Example:

```lua
let A = {V: true};
let B = {V: true};

A.V,B.V = false, false;
```

This will cause a compiler error with the opaque compiler error:

```
Unexpected BinaryExpression (CommaToken)  in compileBinaryExpression roblox-ts/roblox-ts.github.io#2
Please submit an issue at https://github.com/roblox-ts/roblox-ts/issues
```

Edge cases like this, especially when there is a common Lua syntax that isn't supported, should be better handled (since we are pretty much sure Unexpected BinaryExpression (CommaToken), perhaps the error message should be:

```
Unexpected BinaryExpression (CommaToken)  in compileBinaryExpression roblox-ts/roblox-ts.github.io#2
You cannot define multiple variables in a single expression.
```

**Comment by osyrisrblx** [comment]
I agree, this could use a better error message.

But also, your code does something different from what you expected. Here's the "prettified" version:
```TS
let A = { V: true };
let B = { V: true };

A.V, (B.V = false), false;
```
In actual TS, this will only set `B.V` to `false`. Comma listed things are weird in JS..

What you actually wanted was:
```TS
let A = { V: true };
let B = { V: true };

A.V = false, B.V = false;
```

**Comment by Validark** [comment]
This class of issues should be addressed by our [eslint plugin](https://github.com/roblox-ts/lint-rules/). The only change we should make to the compiler is we should whitelist expressions as invalid, so we don't display the unintentional-error message: `(Please submit an issue at https://github.com/roblox-ts/roblox-ts/issues)`
