### ISSUE TITLE
Watch mode doesn't handle file or export function renames well

### ISSUE THREAD

**Issue by mdnorman** [roblox-ts/roblox-ts#672]
## Version

**roblox-ts:** 0.2.12

**@rbxts/types:** 1.0.235

## Description
When using an IDE that handles renaming files, functions, constants etc., such as WebStorm, roblox-ts doesn't always recompile the files in the correct order to handle dependencies. This causes it to stop processing, and miss compiling some of the files. This can cause major problems when running with Rojo, because some of the files will be built and copied, but it's unclear which ones didn't get built correctly. A restart of `rbxtsc -w` is required in order to pick up the files in the correct order.

## Minimal Reproduction
1. Run `rbxtsc -w` and wait for initial compile.
2. Rename an exported function that's used in another file, in an editor such as Webstorm that does all of the saves at the same time.

**Expected behavior:**
`rbxtsc -w` should determine the dependency order and compile files in the correct order, such as the initial compile does.

**Current behavior:**
`rbxtsc -w` will fail if it compiles one of the files that is using the refactored method, and it won't try to compile any other files.

**Comment by Validark** [comment]
Related: https://github.com/roblox-ts/roblox-ts/issues/285
Attempted fix: https://github.com/roblox-ts/roblox-ts/commit/30dd26482501075037d04543f7470be3134b0f42
