### ISSUE TITLE
Increase (default) output verbosity when compiling

### ISSUE THREAD

**Issue by ddavness** [roblox-ts/roblox-ts#673]
## The Problem

Currently, the compiler can take a long while to finish compiling the whole project *(Image stolen from @Vorlias)*:

![image](https://user-images.githubusercontent.com/45321798/64130492-86c24300-cdba-11e9-8eba-f01ca7ae179e.png)

Usability-wise, this is a problem - not giving any feedback within 50 seconds of operation is not desirable. The user will have no idea:

- If the compiler is working at all;
- When will the compilation be done (an estimate of how long);
- What is the compiler even doing, and to what file.

## Suggestion

Increase how much data the compiler outputs while operating. Examples given are:

- Per-file compilation times;
- A progress bar;
- Warm-up times;
- Etc.

If possible, this should be the default verbosity level, which should be adjusted (possibly related to #602)

## Examples

The format below can be discussed, but the idea shouldn't be too far from this:

```
Your/CommandLine/Prompt> rbxtsc -w
Warm-Up time: 123ms
Running in watch mode...
Starting initial compile...
Compiling 5 files:
* file1.ts ... Done, took 1234ms!
* file2.ts ... Done, took 2704ms!
* Folder/anotherone.ts ... Done, took 1337ms!
* filee.ts ... Error!
filee.ts:56 - Diagnostic Error: Property 'FO' does not exist on type 'CameraSettings'.
Took 513ms!
* small.ts ... Done, took 79ms!
Done, took 5867ms!
---- User saves a file ----
Compiling file1.ts ... Done, took 1230ms!
---- User saves a file that triggers multiple files to be recompiled ----
Compiling 2 files:
* Folder/anotherone.ts ... Done, took 900ms!
* file2.ts ... Done, took 2309ms!
Done, took 3209ms!
```

**Comment by Validark** [comment]
Another potential part of a solution is we could hash files and if they haven't changed, we won't compile them. This should speed up compilation for big projects for people like Vorlias, who I'm sure doesn't touch most of the files most of the time `rbxtsc -w` is run.

**Comment by ddavness** [comment]
That's also a valid approach, but not without an argument that allows you to bypass that check (e.g. if you updated the compiler, you probably want to perform a general recompile `rbxtsc -w -force`), at which point the suggestion mentioned above also should come into play.

**Comment by Vorlias** [comment]
Well, you'd store the compiler version as part of the hash file so that
there's a full compile if the versions don't match.
