### ISSUE TITLE
Using nested ... functions with special types results in compilation problems

### ISSUE THREAD

**Issue by filimunger** [roblox-ts/roblox-ts#698]
## Version
**roblox-ts:** 0.2.14
**@rbxts/types:** 1.0.273

## Description
given in title

## Minimal Reproduction
check playground

**Expected behavior:**
more than likely it should just compile the same as the more simple pattern

**Current behavior:**
the more advanced class function errors during run-time

## Playground link
https://roblox-ts.github.io/playground/#code/DYUwLgBAZgdgjAXgBQDo0EMBOBzAzgLggFcYBrGAewHcYBtAXQEoEA+AbwCgOBfD0SWMjQoseQiXLU6TVpwCQsOKgw5cjHhwD0miADdcHAMbB0uXBAAiIALYUAwibMR5AJRLKRqwgDEShsACWFDAAgjhE1iAwYLgAPGAAFgG4tADk3jCp9CyMzhxyconJKBkeomr5vHKlwuXiZJQ0DLnyvNxAA

**Comment by Validark** [comment]
Looks like https://github.com/roblox-ts/roblox-ts/issues/567 came back from the dead.

**Comment by osyrisrblx** [comment]
Looks like this got fixed at some point...?
