### ISSUE TITLE
Add Function.call and Function.bind

### ISSUE THREAD

**Issue by Validark** [roblox-ts/roblox-ts#718]
## Suggestion

We should add methods that mirror JS' `Function.call` and `Function.bind` methods. This would allow developers to have the same freedom to call functions in the same way as they would in Lua. `Function.call` allows one to pass in a custom `this` parameter to methods. This would allow users to not have to lie if this is what they intend to do. We could also add lint rules to make sure one doesn't use `.call` on a callback.

`Function.bind` is a nice built-in currying method. We would probably also need two `bind` methods, one for wrapping callbacks and one for wrapping methods, since the default `bind` expects a `this` parameter, and not all of our functions need one. Again, a lint rule would verify you are using the right one.

## Examples

```ts
const o = {
	f(n: number) {
		return this.g("Hello");
	},
	g: (x: string) => x.slice(0, 3)
};

o.f.call(o, 5);
// maybe bindMethod for methods?
o.f.bindMethod(o, 5)();

function f(n: number) {
}

f.bind(5)
```

**Comment by Dionysusnu** [comment]
Add as macro in refactor?
