### ISSUE TITLE
String enums not handled correctly

### ISSUE THREAD

**Issue by LouieK22** [roblox-ts/roblox-ts#72]
```ts
// String enums
export enum Soups {
    Tomato = "TOMATO",
    ChickenNoodle = "CHICKENNOODLE",
    Dumpling = "DUMPLING",
}
```
compiles to
```lua
Soups = Soups or {};
do
    Soups.Tomato = "TOMATO";
    Soups.ChickenNoodle = "CHICKENNOODLE";
    Soups.Dumpling = "DUMPLING";
end
```
It's not mapping TOMATO to Tomato and so on

**Comment by osyrisrblx** [comment]
This mirrors how TS is compiled to JS, so I _think_ this is how it's intended to work. Going to close this for now. We can reopen it if you find a reason for why this might be incorrect.
