### ISSUE TITLE
Enum string literal escaped double quote transpiles incorrectly

### ISSUE THREAD

**Issue by Vorlias** [roblox-ts/roblox-ts#723]
## Version

**roblox-ts:** roblox-ts@next (commit 8751181ee11a8766dbacf39207c9ac699a8cc96e)

## Description
When enum literal values are transpiled, they do not handle escapes correctly.

## Minimal Reproduction
```ts
enum Test {
    Quote = "\""
}
```
will output as
```lua
Test = Test or {};
do
	Test.Quote = """;
end;
```

**Expected behavior:**
Transpiled string should be "\\""

**Current behavior:**
Transpiled string outputs as """ instead of "\\"".

## Playground link
[Link here](https://roblox-ts.github.io/playground/#code/KYOwrgtgBAKsDOAXKBvAUFTUCKYD2iwUAvFAEQA6ZZaAvkA).

**Comment by Vorlias** [comment]
Also happens with `const enum`.

https://roblox-ts.github.io/playground/#code/MYewdgzgLgBApmArgWxgFTtGBvAUDAmARURCjhgF4YAiAHRptwF9ddRJZzoBLMAcyrpMUAHQkycANxA

**Comment by Validark** [comment]
Looks like the strings aren't handled like how we normally handle strings.

https://github.com/roblox-ts/roblox-ts/blob/24095be38ac0c3e588c9d2bf1f171b7f82f080c4/src/compiler/enum.ts#L24-L29
https://github.com/roblox-ts/roblox-ts/blob/24095be38ac0c3e588c9d2bf1f171b7f82f080c4/src/compiler/indexed.ts#L185-L189
