### ISSUE TITLE
[JSX] Nested conditional attribute inside BinaryConditional expression emits broken code

### ISSUE THREAD

**Issue by Vorlias** [roblox-ts/roblox-ts#761]
## Version

**roblox-ts:** next

## Description
Nesting a conditional statement inside a binary JSX conditional causes broken emit.

## Minimal Reproduction
```ts
		{keyBinding && (
			<textlabel
				BackgroundTransparency={1}
				Position={new UDim2(0, 3, 0, 1)}
				Size={new UDim2(1, -6, 1, -2)}
				Text={slotId}
				TextColor3={
					boundTo
						? Color3.fromRGB(220, 220, 220)
						: Color3.fromRGB(50, 50, 50)
				}
				Font={Enum.Font.Fantasy}
				TextSize={20}
				TextXAlignment={Enum.TextXAlignment.Left}
				TextYAlignment={Enum.TextYAlignment.Bottom}
				TextStrokeTransparency={0.5}
			/>
		)}
```

**Expected behavior:**
The conditional should not be inside the table. 

**Current behavior:**
(Example emit, which is incorrect: )
```lua
			{ 	local _3;
				if boundTo then
					_3 = Color3.fromRGB(220, 220, 220);
				else
					_3 = Color3.fromRGB(50, 50, 50);
				end;
keyBinding and (Roact.createElement(
		"TextLabel",
		{
				BackgroundTransparency = 1,
				Position = UDim2.new(0, 3, 0, 1),
				Size = UDim2.new(1, -6, 1, -2),
				Text = slotId,
				TextColor3 = _3,
				Font = Enum.Font.Fantasy,
				TextSize = 20,
				TextXAlignment = Enum.TextXAlignment.Left,
				TextYAlignment = Enum.TextYAlignment.Bottom,
				TextStrokeTransparency = 0.5,
			}
		)) or nil }
```

This is probably due to the proceeding statement for the binary conditional causing the other conditional to be on the same line. Might be a bit hacky to do it this way in the first place.

Will have to figure out a fix for this, or maybe @Validark might know how to fix this.

## Playground link
(cannot be done on playground due to Roact usage)

**Comment by Vorlias** [comment]
(I apologise if this isn't easy to follow, I would do a playground link but can't because Roact code)

**Comment by Validark** [comment]
There are a number of ways this could be fixed. The standard way of fixing this, by the way, is to open a new context where you want precedingStatements to drop in and then compile the code that could have them, then exit the context.

The best way to fix this is going to be with https://github.com/roblox-ts/roblox-ts/pull/681. This is the most efficient compilation of it:

```lua
local _0 = keyBinding;
if _0 then
	local _1 = {};
	_1.BackgroundTransparency = 1;
	_1.Position = UDim2.new(0, 3, 0, 1);
	_1.Size = UDim2.new(1, -6, 1, -2);
	_1.Text = slotId;
	if boundTo then
		_1.TextColor3 = Color3.fromRGB(220, 220, 220);
	else
		_1.TextColor3 = Color3.fromRGB(50, 50, 50);
	end
	_1.Font = Enum.Font.Fantasy;
	_1.TextSize = 20;
	_1.TextXAlignment = Enum.TextXAlignment.Left;
	_1.TextYAlignment = Enum.TextYAlignment.Bottom;
	_1.TextStrokeTransparency = 0.5;
	_0 = Roact.createElement("TextLabel", _1);
end
```

For now, you could use a Map:
```ts
const boundToColor = new Map([
    [true, Color3.fromRGB(220, 220, 220)],
    [false, Color3.fromRGB(50, 50, 50)]
]);
```
Or an IIFE
```ts
(() => boundTo ? Color3.fromRGB(220, 220, 220) : Color3.fromRGB(50, 50, 50))()
```

**Comment by Validark** [comment]
Side node: is `or nil` supposed to be there?

**Comment by Vorlias** [comment]
> 
> 
> Side node: is `or nil` supposed to be there?

I think there was a weird behaviour if it wasn't there, IIRC.
