### ISSUE TITLE
Implement TS 3.7 Features

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#771]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#optional-chaining
- [ ] ?.
- [ ] ?.[0]
- [ ] ?.()

https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#nullish-coalescing
- [ ] ??

**Comment by Validark** [comment]
I like how this issue looks like you are clueless because of all the question marks, hahaha
