### ISSUE TITLE
Issue with formatting

### ISSUE THREAD

**Issue by matthewJ19** [roblox-ts/roblox-ts#810]
## Version

**roblox-ts:** 0.3.0

**@rbxts/types:** 1.0.275

## Description
While creating an object containing parameters that a function (function not included in this reproduction or playground) would later on modify, I encountered a formatting bug. To test the bug even further, Osyris took my code and condensed it into more objects to intensify the bug even more.

## Minimal Reproduction
https://i.imgur.com/lh9Kk6Q.png
https://i.imgur.com/mBG7E7a.png
```TypeScript
{
	{
		{
			let {
				folder,
				array = new Map<string, unknown>(),
				valids = new Map<string, unknown>([["ValueBase", true]]),
				ignore = new Map<string, Instance>(),
				fName = false,
				useCamel = false,
			} = {} as any;
		}
	}
}
```

**Expected behavior:**
I expected the compiled Lua to be formatted correctly rather than slapping tabs in one line.

**Current behavior:**
The compiled Lua fails to format correctly and most of the content, tabs included, are on the same line rather than creating new lines like it is supposed to.

## Playground link
[https://roblox-ts.github.io/playground/#code/N4KAkKYeUDYKYBcAEkpgGYHtYBN4BOANDFAIYEFkCeyAvMgHbwDuyAsmQA4A8AzogIBLRgHMiyAK6MA1oywtGAPgAUAShLowANzKwhuPvSasO3foJHips+YtUBtBwCIAansnwAQmT7xnEoKeALrBGqRgQqLyBPDGzGycvALCYhIAkowCZIwAxvCq4VoYAHJkALZxDBh6fprokn4AwhXwsMY1sHWkAL7GwH2+yDnUANwwPeCTk0A]().

**Comment by osyrisrblx** [comment]
Also we should ban destructuring from `any`
