### ISSUE TITLE
"rootDirs" Flag Is Not Recognised.

### ISSUE THREAD

**Issue by Barisukan** [roblox-ts/roblox-ts#900]
## Version

**roblox-ts:** 0.3.0
**@rbxts/types:** 1.0.275

## Description
Instead of using "rootDir" in tsconfig.json, opting for "rootDirs" leads to RobloxTS not recognising that the flag exists and instead errors stating that "rootDir" is not present and that it needs to be set. 

## Minimal Reproduction

1. Create a folder in your project called "example"
2. Open up the tsconfig.json for that project
3. Change "rootDir": "src", to
```json
"rootDirs": [
    "src",
    "example"
],
```

**Expected behavior:**
The expectation was that RobloxTS would behave just like TS where it would use both directories as roots to build out the structure used in "out".

**Current behavior:**
RobloxTS ignores "rootDirs" and complains about the non-existence of "rootDir"

**Comment by GeckoCoder** [comment]
Hi, Any update on this? since it is required to set the `isolatedModules` to `true`.
I can not find a work around for a multi place setup.

I found this project https://github.com/roblox-ts/demo-multiplace-game but this makes use of the `rbxtsc-dev` transpiler instead of the `rbxtsc`

**Comment by osyrisrblx** [comment]
@GeckoCoder Both of these problems will get resolved with the new `refactor` branch. Hoping to ship that soon.
