### ISSUE TITLE
Support sparse arrays

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#91]
Currently this doesn't work because .length uses # on the Lua side of things.

**Comment by Validark** [comment]
`table.getn`?

**Comment by Validark** [comment]
We are going to want to use a variable `n` like later versions of lua uses for `table.pack` and such

**Comment by osyrisrblx** [comment]
Considered this implementation, but I'm not sure it's feasible.

Sure, it works for array literals and arrays that the compiler constructs. But arrays given by Roblox API functions and lua libraries wouldn't really work.
