### ISSUE TITLE
Add pnpm option to init

### ISSUE THREAD

**Issue by Dionysusnu** [roblox-ts/roblox-ts#962]
## Suggestion
Add an option to use pnpm instead of npm for installing @rbxts/types, and maybe the option to install dependencies manually.
for example `rbxtsc init model -d pnpm`, where d is one of
- "npm", default
- "pnpm"
- "off"

## Use Cases
Currently the rbxtsc init command always runs
`npm init -y` [here](https://github.com/roblox-ts/roblox-ts/blob/4950df6ba30b790be1a3abe1e159dc4f12d6fb33/src/Initializer.ts#L55)
and
`npm i -D @rbxts/types` [here](https://github.com/roblox-ts/roblox-ts/blob/4950df6ba30b790be1a3abe1e159dc4f12d6fb33/src/Initializer.ts#L59)
Both of which can be unwanted.
The package init is only useful for simple projects, I always make it myself, only for it to then be overwritten by running init
The dependency install is very annoying if using pnpm, because
- I already have them installed manually.
- npm takes up much more disk space than pnpm, by installing every package in every project you have.
- pnpm removes the packages that npm installs.

### Current case
I have my package.json file edited manually, done.
I have installed dependencies using `pnpm install`.
I run `rbxtsc init`, which overwrites both things above.
I then have to run `pnpm install` again to properly install the dependencies.
### New case
I have my package.json file edited manually, done.
I have installed dependencies using `pnpm install`.
I run `rbxtsc init -d off`, which does not touch package.json and does not run npm.

**Comment by osyrisrblx** [comment]
Now that the compiler has been rewritten, this is still a concern but will need to have a few things addressed first:

Symlinks in node_modules doesn't work properly right now.
I think RojoResolver and MacroManager will both need to be fixed for this to work.

**Comment by osyrisrblx** [comment]
Closing this out for now since there's little demand.

**Comment by Picoseconds** [comment]
no plz.
